# Workflow 1, Module 3a

Given a disease, first find chemical agents that make the disease worse. Then look for genes that decrease the amount of or response to the toxicant, and try to increase the amount or action of those genes.

In [12]:
input_disease = 'MONDO:0005148'  #Type 2 diabetes

## Functions

In [13]:
import requests
import pandas as pd

robokop_server = 'robokop.renci.org'

def quick(question):
    url=f'http://{robokop_server}:80/api/simple/quick/'
    response = requests.post(url,json=question)
    print( f"Return Status: {response.status_code}" )
    if response.status_code == 200:
        return response.json()
    return response

In [14]:
def make_N_step_question(types,curies,props,forwards):
    question = {
                'machine_question': {
                    'nodes': [],
                    'edges': []
                }
            }
    for i,t in enumerate(types):
        newnode = {'id': f'n{i}', 'type': t}
        if curies[i] is not None:
            newnode['curie'] = curies[i]
        question['machine_question']['nodes'].append(newnode)
        if i > 0:
            if forwards[i-1]:
                edge = {'id': f'e{i}', 'source_id': f'n{i-1}', 'target_id': f'n{i}'}
            else:
                edge = {'id': f'e{i}', 'source_id': f'n{i}', 'target_id': f'n{i-1}'}
            if props[i-1] is not None:
                edge['type'] = props[i-1]
            question['machine_question']['edges'].append( edge )
    return question

In [15]:
def merge_answers(answerdict):
    """Take a dictionary of answer lists and return a single sorted answer list."""
    final_answer = {'misc_info': {'natural_question': None, 'num_total_paths': 0}, 'answers': []}
    for k,v in answerdict.items():
        if 'filename' in v: 
            final_answer['filename'] = v['filename']
        if 'timestamp' in v:
            final_answer['timestamp'] = v['timestamp']
        if 'misc_info' in v:
            final_answer['misc_info']['num_total_paths'] += v['misc_info']['num_total_paths']
        if 'answers' in v:
            final_answer['answers'].extend(v['answers'])
    final_answer['answers'].sort(key = lambda a: -a['score'])

    return final_answer

In [16]:
import pandas as pd
def answers2frame(graph_answers,properties_a,properties_b):
    answers = []
    for graph_answer in graph_answers['answers']:
        try:
            #The return nodes don't necessarily come out in order. We can recognize the disease and the gene
            # by type, but we have to get the original toxicant by finding which node has the correct id.
            if len(graph_answer['nodes']) < 4:
                continue
            for edge in graph_answer['edges']:
                if edge['type']=='contributes_to':
                    toxicant_id = edge['source_id']
                elif edge['type'] in properties_a:
                    gene_tox = edge
                elif edge['type'] in properties_b:
                    chem_gene = edge
            for node in graph_answer['nodes']:
                if node['type'] == 'gene':
                    gene = node
                elif node['type'] == 'chemical_substance':
                    if node['id'] == toxicant_id:
                        toxicant=node
                    else:
                        drug=node
            ans = { 'score': graph_answer['score'],
                    'toxicant': toxicant['name'] if 'name' in toxicant else toxicant['id'],
                    'gene': gene['name'] if 'name' in gene else gene['id'],
                    'chemical': drug['name'] if 'name' in drug else drug['id'],
                    'gene->toxicant': gene_tox['type'],
                    'chem->gene': chem_gene['type']}
        except IndexError:
            #this happens if chemical and toxicant are the same thing
            continue
        answers.append(ans)
    df = pd.DataFrame(answers)
    ordered_columns = ['score','chemical','chem->gene','gene','gene->toxicant','toxicant']
    df = df[ordered_columns]
    return df

## Set up the property lists

There are several properties at each step that are acceptable for our purposes. 

In [17]:
properties_a=['increases_degradation_of',
              'decreases_abundance_of',
              'decreases_response_to',
              'increases_uptake_of']
properties_b=['increases_activity_of',
              'increases_expression_of',
              'decreases_degradation_of',
              'increases_stability_of',
              'increases_synthesis_of',
              'increases_secretion_of'
                ]
types = ['disease',
        'chemical_substance',
        'gene',
        'chemical_substance']
curies = [input_disease,None,None,None]
forwards = [False,False,False]

In [18]:
single_q = make_N_step_question(types,curies,['contributes_to',properties_a,properties_b],forwards)
single_answer = quick(single_q)

Return Status: 200


In [19]:
df = answers2frame(single_answer,properties_a,properties_b)

In [20]:
from IPython.display import display
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df)

score                  chemical               chem->gene     gene  \
0    1.927600                 metformin  increases_expression_of   SLC2A4   
1    1.713251               cholesterol    increases_activity_of     MYLK   
2    1.543229                   glucose   increases_secretion_of      IL6   
3    1.493152                   glucose   increases_secretion_of     IL1B   
4    1.487819                   glucose   increases_secretion_of      IL6   
5    1.463625             rosiglitazone  increases_expression_of   SLC2A4   
6    1.458299                   glucose  increases_expression_of    PTGS2   
7    1.426568             rosiglitazone  increases_expression_of     UCP1   
8    1.418777                   glucose   increases_secretion_of      TNF   
9    1.409878                   glucose    increases_activity_of      EGF   
10   1.395155                   glucose   increases_secretion_of      TNF   
11   1.390928                   glucose   increases_secretion_of     CCL2   
12   1.384906                   glucose    increases_activity_of     RELA   
13   1.365866                 metformin    increases_activity_of      CAT   
14   1.359609                 metformin    increases_activity_of      CAT   
15   1.317791                   glucose   increases_secretion_of    TGFB1   
16   1.314547               cholesterol  increases_expression_of      APP   
17   1.310338                   glucose    increases_activity_of      AGT   
18   1.302923                   glucose    increases_activity_of      AGT   
19   1.287761             rosiglitazone    increases_activity_of     SOD2   
20   1.282415                   glucose  increases_expression_of     EDN1   
21   1.274303                     lipid    increases_activity_of      AHR   
22   1.270713                   glucose   increases_secretion_of      VIM   
23   1.266932                 metformin    increases_activity_of      CAT   
24   1.265122                   glucose  increases_expression_of   SLC2A5   
25   1.250808                   glucose  increases_expression_of     NCF1   
26   1.247774                   glucose    increases_activity_of   MAPK14   
27   1.228076                     lipid    increases_activity_of      AHR   
28   1.221131                   glucose   increases_secretion_of    CXCL8   
29   1.215675                 glyburide   increases_secretion_of      INS   
30   1.209510                   glucose    increases_activity_of      EGF   
31   1.078811                  cortisol  increases_expression_of      INS   
32   1.059292              pioglitazone    increases_activity_of    PPARG   
33   1.048185   reactive oxygen species    increases_activity_of      TNF   
34   1.013170             rosiglitazone    increases_activity_of    PPARG   
35   1.005888             rosiglitazone  increases_expression_of    HMOX1   
36   0.986397               tolbutamide  increases_expression_of   SLC2A1   
37   0.978344             rosiglitazone    increases_activity_of     SOD2   
38   0.976733               tolbutamide   increases_secretion_of      INS   
39   0.963019                   ethanol    increases_activity_of     SOD2   
40   0.948578             rosiglitazone  increases_expression_of    NR1H3   
41   0.935249              troglitazone  increases_expression_of   SLC2A1   
42   0.929546   reactive oxygen species    increases_activity_of     SOD1   
43   0.916515             rosiglitazone  increases_expression_of    HMOX1   
44   0.895907         hydrogen peroxide    increases_activity_of     SOD2   
45   0.882911             rosiglitazone    increases_activity_of      AGT   
46   0.878803             rosiglitazone    increases_activity_of      AGT   
47   0.878206   reactive oxygen species    increases_activity_of      TNF   
48   0.845732              troglitazone    increases_activity_of      INS   
49   0.824367              cadmium atom   increases_secretion_of      IL6   
50   0.817963                 zinc atom   increases_secretion_of      TNF   
51  

The first hit is for metformin, a known diabetes drug, and it's because it increases the uptake of glucose (the toxicant in this case).  The gene is interesting, because it is SLC2A4, rather than the expected INS (insulin).  This is probably due to the source of the data.

Both glucose and cholesterol also show up in the chemical column, which is meant to be the potential treatment!   This seems counterintuitive, but what we are seeing is that the query is too simple.  The question posits a linear relationship: there is a toxicant, the action of a gene gets rid of the toxicant, and the treatment makes the gene do this more. 

But actual biology is not so simple!  Specifically, feedback loops substantially complicate the picture.  If a gene is involved in cleaning up a toxicant, then the presence of that toxicant usually stimulates the gene.  So it's no suprise to see glucose on the treatment side, as it does tend to stimulate the metabolic processes that are disregulated in diabetes.

We don't have the ability to model things so directly, but we can at least filter out rows where the chemical has a known causal effect on diabetes.  We'd also like to flag answers that are already known diabetes treatments.

In [21]:
#Get chemicals that contribute to the disease
cq=make_N_step_question(['disease','chemical_substance'],[input_disease,None],['contributes_to'],[False])
aq=quick(cq)

Return Status: 200


In [22]:
contributors = []
for answer in aq['answers']:
    nodes = answer['nodes']
    for node in nodes:
        if node['type'] == 'chemical_substance':
            contributors.append(node)
df_contributors = pd.DataFrame(contributors)
df_contributors = df_contributors[['name']]
df_contributors['contributors']=True

In [23]:
#Get treatments for the disease
tq=make_N_step_question(['disease','chemical_substance'],[input_disease,None],['treats'],[False])
ta=quick(tq)
treatments = []
for answer in ta['answers']:
    nodes = answer['nodes']
    for node in nodes:
        if node['type'] == 'chemical_substance':
            treatments.append(node)
df_treatments = pd.DataFrame(treatments)
df_treatments = df_treatments[['name']]
df_treatments['treatments']=True

Return Status: 200


In [24]:
#Merge in the contributors and treatments.
dfx = pd.merge(df,df_contributors,left_on='chemical',right_on='name',how='left')
dfx = pd.merge(dfx,df_treatments,left_on='chemical',right_on='name',how='left')
dfx = dfx.sort_values(by='score',ascending=False)
dfx.fillna(False,inplace=True)
del dfx['name_x']
del dfx['name_y']

It's messy and counterintiutive, but we need to be aware that sometimes the same chemical can be listed as both a contributor and a treatment:

In [27]:
dfx[(dfx.contributors==True) & (dfx.treatments==True)].head()

score       chemical              chem->gene  gene  \
29  1.215675      glyburide  increases_secretion_of   INS   
50  0.817963      zinc atom  increases_secretion_of   TNF   
56  0.774992      zinc atom  increases_secretion_of   TNF   
60  0.769019  chromium atom  increases_secretion_of   IL6   
63  0.765397      zinc atom   increases_activity_of  MTF1   

           gene->toxicant      toxicant  contributors  treatments  
29    increases_uptake_of       glucose          True        True  
50    increases_uptake_of     iron atom          True        True  
56    increases_uptake_of  cadmium atom          True        True  
60    increases_uptake_of     zinc atom          True        True  
63  decreases_response_to  cadmium atom          True        True

In [29]:
dfx_no_contrib = dfx[ (dfx.contributors == False) | (dfx.treatments == True)]
dfx_no_contrib

score                  chemical               chem->gene    gene  \
0    1.927600                 metformin  increases_expression_of  SLC2A4   
1    1.713251               cholesterol    increases_activity_of    MYLK   
5    1.463625             rosiglitazone  increases_expression_of  SLC2A4   
7    1.426568             rosiglitazone  increases_expression_of    UCP1   
13   1.365866                 metformin    increases_activity_of     CAT   
14   1.359609                 metformin    increases_activity_of     CAT   
16   1.314547               cholesterol  increases_expression_of     APP   
19   1.287761             rosiglitazone    increases_activity_of    SOD2   
21   1.274303                     lipid    increases_activity_of     AHR   
23   1.266932                 metformin    increases_activity_of     CAT   
27   1.228076                     lipid    increases_activity_of     AHR   
29   1.215675                 glyburide   increases_secretion_of     INS   
31   1.078811                  cortisol  increases_expression_of     INS   
32   1.059292              pioglitazone    increases_activity_of   PPARG   
33   1.048185   reactive oxygen species    increases_activity_of     TNF   
34   1.013170             rosiglitazone    increases_activity_of   PPARG   
35   1.005888             rosiglitazone  increases_expression_of   HMOX1   
36   0.986397               tolbutamide  increases_expression_of  SLC2A1   
37   0.978344             rosiglitazone    increases_activity_of    SOD2   
38   0.976733               tolbutamide   increases_secretion_of     INS   
39   0.963019                   ethanol    increases_activity_of    SOD2   
40   0.948578             rosiglitazone  increases_expression_of   NR1H3   
41   0.935249              troglitazone  increases_expression_of  SLC2A1   
42   0.929546   reactive oxygen species    increases_activity_of    SOD1   
43   0.916515             rosiglitazone  increases_expression_of   HMOX1   
44   0.895907         hydrogen peroxide    increases_activity_of    SOD2   
45   0.882911             rosiglitazone    increases_activity_of     AGT   
46   0.878803             rosiglitazone    increases_activity_of     AGT   
47   0.878206   reactive oxygen species    increases_activity_of     TNF   
48   0.845732              troglitazone    increases_activity_of     INS   
..        ...                       ...                      ...     ...   
178  0.605442              progesterone  increases_expression_of  SLC2A1   
180  0.602370              troglitazone    increases_activity_of  CYP3A4   
182  0.601400              troglitazone  increases_expression_of   HMOX1   
183  0.599261              testosterone  increases_expression_of     TNF   
184  0.598805         hydrogen peroxide    increases_activity_of   PTGS2   
185  0.598358                    phenol   increases_secretion_of     TNF   
186  0.596630                     azide    increases_activity_of  SLC2A1   
189  0.594910                 quercetin    increases_activity_of   SIRT1   
190  0.593680               simvastatin   increases_secretion_of     TNF   
192  0.593498           silicon dioxide   increases_secretion_of     IL6   
193  0.593297        lipopolysaccharide   increases_secretion_of     IL6   
194  0.591971               simvastatin    increases_activity_of   HMGCR   
195  0.591272              testosterone  increases_expression_of     TNF   
197  0.589405              testosterone  increases_expression_of    BCL2   
198  0.587837         trans-resveratrol    increases_activity_of     CAT   
199  0.585546               cobalt atom    increases_activity_of  NFE2L2   
201  0.584780             valproic acid  increases_expression_of  SLC2A1   
203  0.583936        lipopolysaccharide   increases_secretion_of     TNF   
204  0.583176            benzo[a]pyrene    increases_activity_of     CAT   
205  0.583155          arachidonic acid   increases_secretion_of     INS   
206  0.582499               simvastatin   increases_secr

Just to make this a little easier to read, let's just keep the first row whenever we find a new chemical.  So for instance, we'll keep the first metformin above, but not any others. This potentially hides some extra evidence for a chemical, so use with caution, but it makes it easier to get an overall view of what chemicals are found.  It's ok to get the first row because the frame is already sorted by score.

In [30]:
dfx_no_contrib.groupby('chemical').nth(0).reset_index().sort_values(by='score',ascending=False)

chemical               chem->gene  contributors    gene  \
24                 metformin  increases_expression_of         False  SLC2A4   
8                cholesterol    increases_activity_of         False    MYLK   
33             rosiglitazone  increases_expression_of         False  SLC2A4   
21                     lipid    increases_activity_of         False     AHR   
19                 glyburide   increases_secretion_of          True     INS   
12                  cortisol  increases_expression_of         False     INS   
29              pioglitazone    increases_activity_of         False   PPARG   
32   reactive oxygen species    increases_activity_of         False     TNF   
40               tolbutamide  increases_expression_of         False  SLC2A1   
17                   ethanol    increases_activity_of         False    SOD2   
42              troglitazone  increases_expression_of         False  SLC2A1   
20         hydrogen peroxide    increases_activity_of         False    SOD2   
44                 zinc atom   increases_secretion_of          True     TNF   
27                 phlorizin   increases_stability_of         False  SLC5A1   
9              chromium atom   increases_secretion_of          True     IL6   
11               cobalt atom   increases_secretion_of         False     IL6   
1                        ATP  increases_expression_of         False     IL6   
7                carbon atom   increases_secretion_of         False     TNF   
14             dexamethasone  increases_expression_of         False   FOXO1   
22        lipopolysaccharide    increases_activity_of         False    SOD2   
45                zinc oxide   increases_secretion_of         False     IL6   
41         trans-resveratrol    increases_activity_of         False   SIRT1   
15                  dopamine    increases_activity_of         False    DRD3   
28                 phosphate   increases_secretion_of         False     PTH   
6                  biguanide    increases_activity_of         False     CAT   
0           17beta-estradiol    increases_activity_of         False    SOD2   
16               doxorubicin    increases_activity_of         False     CAT   
23                 melatonin    increases_activity_of         False    SOD2   
34                  rotenone    increases_activity_of         False    SOD2   
35           silicon dioxide   increases_secretion_of         False     TNF   
25               nateglinide   increases_secretion_of         False     INS   
36               simvastatin   increases_stability_of         False   HMOX1   
39              testosterone  increases_expression_of         False   PTGS2   
2              acetylcholine   increases_secretion_of         False     INS   
37               terbutaline  increases_expression_of         False     INS   
30              progesterone  increases_expression_of         False  SLC2A1   
26                    phenol   increases_secretion_of         False     TNF   
4                      azide    increases_activity_of         False  SLC2A1   
31                 quercetin    increases_activity_of         False   SIRT1   
43             valproic acid  increases_expression_of         False  SLC2A1   
5             benzo[a]pyrene    increases_activity_of         False     CAT   
3           arachidonic acid   increases_secretion_of         False     INS   
13             cyclosporin A  increases_expression_of         False  SLC2A1   
10                clofibrate    increases_activity_of         False     CAT   
18               fenofibrate    increases_activity_of         False     CAT   
38  tert-butyl hydroperoxide    increases_activity_of         False    SOD2   

           gene->toxicant     score               toxicant  treatments  
24    increases_uptake_of  1.927600                glucose        True  
8     increases_uptake_of  1.713251                glucose       False  
33    increases_uptake_of  1.463625                glucose        True  
21  decreases_

Our attempt to remove known contributors was mostly successful.  However, it was imperfect because these annotations of contributor and treatment are imperfect.  In particular, while things like HDL and LDL are listed as contributors, the more general terms cholesterol and lipid are not.  Other answers that should probably be understood as finding chemicals that make diabetes worse are cortisol (a stress-hormone that increases glucose) and reactive oxygen species, including hydrogen peroxide.   Let's remove all of these as well.

In [31]:
moretox = ['cholesterol','lipid','cortisol','reactive oxygen species','hydrogen peroxide']
newdfx = dfx_no_contrib[ ~dfx_no_contrib.chemical.isin(moretox)]
#And choose first row of each chemical
newdfx.groupby('chemical').nth(0).reset_index().sort_values(by='score',ascending=False)

chemical               chem->gene  contributors    gene  \
20                 metformin  increases_expression_of         False  SLC2A4   
28             rosiglitazone  increases_expression_of         False  SLC2A4   
17                 glyburide   increases_secretion_of          True     INS   
25              pioglitazone    increases_activity_of         False   PPARG   
35               tolbutamide  increases_expression_of         False  SLC2A1   
15                   ethanol    increases_activity_of         False    SOD2   
37              troglitazone  increases_expression_of         False  SLC2A1   
39                 zinc atom   increases_secretion_of          True     TNF   
23                 phlorizin   increases_stability_of         False  SLC5A1   
8              chromium atom   increases_secretion_of          True     IL6   
10               cobalt atom   increases_secretion_of         False     IL6   
1                        ATP  increases_expression_of         False     IL6   
7                carbon atom   increases_secretion_of         False     TNF   
12             dexamethasone  increases_expression_of         False   FOXO1   
18        lipopolysaccharide    increases_activity_of         False    SOD2   
40                zinc oxide   increases_secretion_of         False     IL6   
36         trans-resveratrol    increases_activity_of         False   SIRT1   
13                  dopamine    increases_activity_of         False    DRD3   
24                 phosphate   increases_secretion_of         False     PTH   
6                  biguanide    increases_activity_of         False     CAT   
0           17beta-estradiol    increases_activity_of         False    SOD2   
14               doxorubicin    increases_activity_of         False     CAT   
19                 melatonin    increases_activity_of         False    SOD2   
29                  rotenone    increases_activity_of         False    SOD2   
30           silicon dioxide   increases_secretion_of         False     TNF   
21               nateglinide   increases_secretion_of         False     INS   
31               simvastatin   increases_stability_of         False   HMOX1   
34              testosterone  increases_expression_of         False   PTGS2   
2              acetylcholine   increases_secretion_of         False     INS   
32               terbutaline  increases_expression_of         False     INS   
26              progesterone  increases_expression_of         False  SLC2A1   
22                    phenol   increases_secretion_of         False     TNF   
4                      azide    increases_activity_of         False  SLC2A1   
27                 quercetin    increases_activity_of         False   SIRT1   
38             valproic acid  increases_expression_of         False  SLC2A1   
5             benzo[a]pyrene    increases_activity_of         False     CAT   
3           arachidonic acid   increases_secretion_of         False     INS   
11             cyclosporin A  increases_expression_of         False  SLC2A1   
9                 clofibrate    increases_activity_of         False     CAT   
16               fenofibrate    increases_activity_of         False     CAT   
33  tert-butyl hydroperoxide    increases_activity_of         False    SOD2   

           gene->toxicant     score               toxicant  treatments  
20    increases_uptake_of  1.927600                glucose        True  
28    increases_uptake_of  1.463625                glucose        True  
17    increases_uptake_of  1.215675                glucose        True  
25  decreases_response_to  1.059292  N-nitrosodiethylamine        True  
35    increases_uptake_of  0.986397                glucose        True  
15  decreases_response_to  0.963019                glucose       False  
37    increases_uptake_of  0.935249                glucose        True  
39    increases_uptake_of  0.817963              iron atom        True  
23    increases_uptake_of  0.770882         

### Notes on the rows that are not already known treatments 

Ethanol: Ethanol can reduce glucose levels, but it's a complicated picture, because it can also increase glucose.  Long-term ethanol can also lead to reduced insulin sensititivy.

Phlorizin: Wikipedia says: Phlorizin was studied as a potential pharmaceutical treatment for type 2 diabetes, but has since been superseded by more selective and more promising synthetic analogs, such as empagliflozin, canagliflozin and dapagliflozin.[8][9] Phlorizin is not an effective drug because when orally consumed, it is nearly entirely converted into phloretin by hydrolytic enzymes in the small intestine.[10][11]

Cobalt: https://www.ncbi.nlm.nih.gov/pubmed/16802070 says "We conclude that chronic cobalt treatment decreases plasma glucose levels in STZ-diabetic rats and improves tolerance to glucose."  Also https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3138145/

ATP: ATP is involved in cell-energy cycles along with glucose

Carbon: ?

Dexamethasone: glucocorticosteroid used to treat asthma, COPD, and many other things. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5503862/ says: "Glucocorticoids are widely used as potent anti-inflammatory and immunosuppressive drugs to treat a wide range of diseases. However, they are also associated with a number of side effects, including new-onset hyperglycemia in patients without a history of diabetes mellitus (DM) or severely uncontrolled hyperglycemia in patients with known DM."

Zinc Oxide: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3958835/: "Antidiabetic Activity of Zinc Oxide and Silver Nanoparticles on Streptozotocin-Induced Diabetic Rats"

Lipopolysaccharide: https://www.ncbi.nlm.nih.gov/pubmed/23835694 "Elevated levels of lipopolysaccharide (LPS) predict incident diabetes"

Dopamine: https://www.sciencedirect.com/science/article/pii/S1751991815001540 "A review of dopamine agonist therapy in type 2 diabetes and effects on cardio-metabolic parameters"  Also https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5945822/

Phosphate: ?

Biguanide: is actually a class of drugs that includes metformin.

Testosterone: Testosterone has been investigated as a diabetic therapy for men, but results seem mixed

doxorubicin: a chemotherapy drug. https://onlinelibrary.wiley.com/doi/full/10.1002/jcsm.12104: "Doxorubicin caused severe hyperglycaemia and insulin resistance, mediated by inhibition in AMPk signalling in skeletal muscle"

17beta-estradiol: female sex hormone.  There's a relation to diabetes & it's been looked at as a therapy, but again results seem mixed, and possibly dependent on menopause

acetylcholine: neurotransmitter involved in glucose homeostasis.  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4113066/

Melatonin: Hormone involved in sleep (and used to treat insomnia).  There's some association with T2D, but it's complicated: https://link.springer.com/article/10.1007/s00125-017-4255-x

terbutaline: beta2 agonist for asthma.  Known to cause hyperglycemia and exacerbate diabetes.  

progesterone: Also a female sex hormone.  A lot of work in this area, but unclear what the relationship is.

phenol: polyphenols have in-vitro antioxidative effects, but also low bioavailability and may or may not have in vivo antioxidant effects 

azide: https://www.sciencedirect.com/science/article/pii/S2211383512000949 lists azide as a mitochondrial inhibitor that may increase insulin sensitivity

quercetin: a flavonoid. https://www.sciencedirect.com/science/article/pii/S0753332218349187 "In vitro and in vivo evidence that quercetin protects against diabetes and its complications: A systematic review of the literature"

valproic acid: anticonvulsant. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5483554/ "Does Valproic Acid Have Potential in the Treatment of Diabetes Mellitus?"  https://www.ncbi.nlm.nih.gov/pubmed/27079868 "Valproic Acid Improves Glucose Homeostasis by Increasing Beta-Cell Proliferation, Function, and Reducing its Apoptosis through HDAC Inhibition in Juvenile Diabetic Rat."

rotenone: an isoflavone used as a pesticide, but: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5783883/ "Rotenone ameliorated hyperglycaemia and insulin resistance in db/db mice. It induced glucose consumption and glycolysis and reduced hepatic glucose output. Rotenone also activated AMPK. Furthermore, it remained effective with AMPK inactivation."

arachidonic acid: a polyunsaturated fat.  Wikipedia:Furthermore, higher concentrations of ARA in muscle tissue may be correlated with improved insulin sensitivity.[ https://www.ncbi.nlm.nih.gov/pubmed/8418404 ].

simvastatin: statins tend to increase diabetic risk, so this probably goes in the contributors column. Note that the toxicant for this row is another statin.

silicon dioxide: ?

cyclosporin: an immunosuppressant.  There is a post-transplant diabetes that happens when tacrolimus is used as an immunosuppressant, and cyclosporin seems to be better?  https://onlinelibrary.wiley.com/doi/abs/10.1111/ajt.14665

fenofibrate: cholesterol medication.

### Rare Diseases

The above was all carried out for type 2 diabetes, a common disease.  Here we try to run the same thing but for rare forms of diabetes (as found in WF1Mod1_Ontology.ipynb). We're going to try a lot, because the data is sparse for these diseases, and we will see that most of them do not return any results.

In [33]:
rare_diseases = ['MONDO:0014785',
'MONDO:0011986',
'MONDO:0012819',
'MONDO:0012513',
'MONDO:0014458',
'MONDO:0012970',
'MONDO:0013478',
'MONDO:0013242',
'MONDO:0009575',
'MONDO:0016391',
'MONDO:0010802',
'MONDO:0016422',
'MONDO:0012971',
'MONDO:0011955',
'MONDO:0015308',
'MONDO:0014991',
'MONDO:0009517',
'MONDO:0013647',
'MONDO:0011363',
'MONDO:0014523',
'MONDO:0011386',
'MONDO:0017230',
'MONDO:0008763',
'MONDO:0012966',
'MONDO:0012436',
'MONDO:0012348',
'MONDO:0012520',
'MONDO:0007455',
'MONDO:0008812',
'MONDO:0020569',
'MONDO:0018105',
'MONDO:0012818',
'MONDO:0007669',
'MONDO:0014686',
'MONDO:0007452',
'MONDO:0013225',
'MONDO:0007453',
'MONDO:0012480',
'MONDO:0009874',
'MONDO:0013240',
'MONDO:0010020',
'MONDO:0012962',
'MONDO:0012923',
'MONDO:0011502',
'MONDO:0010800',
'MONDO:0014589',
'MONDO:0012963',
'MONDO:0008696',
'MONDO:0011027',
'MONDO:0011273',
'MONDO:0013673',
'MONDO:0018581',
'MONDO:0018911',
'MONDO:0011073',
'MONDO:0010773',
'MONDO:0011667',
'MONDO:0014488',
'MONDO:0011668',
'MONDO:0012192',
'MONDO:0020525',
'MONDO:0019207',
'MONDO:0010785',
'MONDO:0009192',
'MONDO:0018320',
'MONDO:0015967',
'MONDO:0014674',
'MONDO:0000208',
'MONDO:0018625',
'MONDO:0008185',
'MONDO:0009419',
'MONDO:0010894',
'MONDO:0011643',
'MONDO:0012071',
'MONDO:0009101',
'MONDO:0000065',
'MONDO:0018575',
'MONDO:0012969',
'MONDO:0014497',
'MONDO:0018629',
'MONDO:0018883',
'MONDO:0012522',
'MONDO:0010026',
'MONDO:0011072',
'MONDO:0008491']

In [38]:
outputs = {}
for rare_id in rare_diseases:
    rarecuries = [rare_id,None,None,None]
    single_disease_question = make_N_step_question(types,rarecuries,['contributes_to',properties_a,properties_b],forwards)
    rare_answer = quick(single_disease_question)
    if rare_answer == 'No results found':
        npaths = 0
    else:
        npaths = rare_answer['misc_info']['num_total_paths']
    print(rare_id,npaths)
    if npaths > 0:
        outputs[rare_id] = rare_answer

Return Status: 200
MONDO:0014785 0
Return Status: 200
MONDO:0011986 0
Return Status: 200
MONDO:0012819 250
Return Status: 200
MONDO:0012513 0
Return Status: 200
MONDO:0014458 0
Return Status: 200
MONDO:0012970 0
Return Status: 200
MONDO:0013478 0
Return Status: 200
MONDO:0013242 0
Return Status: 200
MONDO:0009575 0
Return Status: 200
MONDO:0016391 0
Return Status: 200
MONDO:0010802 0
Return Status: 200
MONDO:0016422 0
Return Status: 200
MONDO:0012971 0
Return Status: 200
MONDO:0011955 0
Return Status: 200
MONDO:0015308 0
Return Status: 200
MONDO:0014991 0
Return Status: 200
MONDO:0009517 0
Return Status: 200
MONDO:0013647 0
Return Status: 200
MONDO:0011363 0
Return Status: 200
MONDO:0014523 0
Return Status: 200
MONDO:0011386 0
Return Status: 200
MONDO:0017230 0
Return Status: 200
MONDO:0008763 0
Return Status: 200
MONDO:0012966 0
Return Status: 200
MONDO:0012436 0
Return Status: 200
MONDO:0012348 0
Return Status: 200
MONDO:0012520 0
Return Status: 200
MONDO:0007455 0
Return Status: 200

In [39]:
outputs.keys()

dict_keys(['MONDO:0012819', 'MONDO:0008491'])

We only received any responses for `MONDO:0012819` (diabetic ketoacidosis) and `MONDO:0008491` (stiff-person syndrome).  Let's merge the responses.

In [41]:
rare_answers = merge_answers(outputs)
df = answers2frame(rare_answers,properties_a,properties_b)
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df)

score                                           chemical  \
0    0.563518                                           dopamine   
1    0.431542                                            acetone   
2    0.418220                                      phenobarbital   
3    0.412806                                            ethanol   
4    0.389815                                        paracetamol   
5    0.386653                                            benzene   
6    0.385268                                           caffeine   
7    0.384670                                        paracetamol   
8    0.383350                                       chlorpyrifos   
9    0.383068                                      phenobarbital   
10   0.382953                                            toluene   
11   0.380509                                      valproic acid   
12   0.371811                                        haloperidol   
13   0.367849                                         phenacetin   
14   0.366162                                      dexamethasone   
15   0.366140                                            cocaine   
16   0.362567                                            alcohol   
17   0.362399                                           dopamine   
18   0.359195                                    methamphetamine   
19   0.355069                                            aniline   
20   0.350940                                      rosiglitazone   
21   0.341145                                      phenobarbital   
22   0.339491                                           glycerol   
23   0.339359                                      phenobarbital   
24   0.338455                                      phenobarbital   
25   0.338191                                      phenobarbital   
26   0.337894                                          aspartame   
27   0.337769                                      phenobarbital   
28   0.337040                                          hydrazine   
29   0.336691                                      phenobarbital   
30   0.335755                                      valproic acid   
31   0.334628                                      phenobarbital   
32   0.334086                                        amphetamine   
33   0.329822                                       cypermethrin   
34   0.325762                                        simvastatin   
35   0.323696                                          phenytoin   
36   0.322405                                       troglitazone   
37   0.322270                                      phenobarbital   
38   0.322183                                      phenobarbital   
39   0.320532                                           pyridine   
40   0.320133                                          phenytoin   
41   0.318594                                      dexamethasone   
42   0.317742                                 lipopolysaccharide   
43   0.317056                                      carbamazepine   
44   0.314078                                            ethanol   
45   0.312999                                     benzo[a]pyrene   
46   0.310802                                      valproic acid   
47   0.310792                                  hydrogen peroxide   
48   0.310533                                      dexamethasone   
49   0.310528                                        paracetamol   
50   0.308648                                              ozone   
51   0.308551                                        silver atom   
52   0.308401                                       troglitazone   
53   0.308359                                      phenobarbital   
54   0.308354                                           caffeine   
55   0.307209                                      valproic acid   
56   0.306908                                         calcitriol   
57   0.306778                                          zinc atom

In [42]:
#Cull out rows with repeat chemicals
df.groupby('chemical').nth(0).reset_index().sort_values(by='score',ascending=False)

chemical  \
86                                            dopamine   
38                                             acetone   
132                                      phenobarbital   
90                                             ethanol   
126                                        paracetamol   
54                                             benzene   
63                                            caffeine   
68                                        chlorpyrifos   
160                                            toluene   
166                                      valproic acid   
99                                         haloperidol   
129                                         phenacetin   
80                                       dexamethasone   
72                                             cocaine   
42                                             alcohol   
115                                    methamphetamine   
48                                             aniline   
146                                      rosiglitazone   
96                                            glycerol   
51                                           aspartame   
102                                          hydrazine   
47                                         amphetamine   
77                                        cypermethrin   
150                                        simvastatin   
135                                          phenytoin   
165                                       troglitazone   
142                                           pyridine   
109                                 lipopolysaccharide   
66                                       carbamazepine   
55                                      benzo[a]pyrene   
..                                                 ...   
122                                           oltipraz   
92                                            fluorene   
82                                        dibenzofuran   
34                                         Rutecarpine   
113                                          menadione   
118                                        musk xylene   
7                      2,3',4,4',5-Pentachlorobiphenyl   
14             3-Amino-1-methyl-5H-pyrido[4,3-b]indole   
36                                        acenaphthene   
147                                           rotenone   
106                                       isoprenaline   
81                               dibenz[a,h]anthracene   
136                                 potassium chloride   
127                                           paraoxon   
134                                      phenylephrine   
103                                  hydrogen chloride   
17                                                 ATP   
1                                      (S)-amphetamine   
18                                               Acids   
2    (cis)-N-(2-iodobenzyl)-2-benzhydrylquinuclidin...   
27                     N-acetyl-1,4-benzoquinone imine   
43                                allyl isothiocyanate   
137                                  potassium hydride   
20                                       CHEMBL3586009   
123                                 orthoperiodic acid   
22                                         CHEMBL76578   
23                                    Cyclophosphamide   
24                                   Freund's Adjuvant   
25                                            Kallidin   
0                              (E)-4-hydroxynon-2-enal   

                   chem->gene    gene         gene->toxicant     score  \
86      increases_activity_of    DRD3  decreases_response_to  0.563518   
38      increases_activity_of  CYP2E1  decreases_response_to  0.431542   
132     increases_activity_of  CYP1A2  decreases_response_to  0.418220   
90      increases_activity_of  CYP2E1  decreases_response_to  0.412806   
126     increases_activity_of  CYP2E1  decreases_response_to  0.389815   
54   

Overall, this looks like a somewhat less interesting list.  The toxicants are not endogenous chemicals, but are drugs that are probalby contra-indicated for these particular conditions.  So we might end up hooking into reasonable biology, but it's going to be somewhat indirectly.  But, we can make some notes:

dopamine: we noted above that several dopminergic compounds appeared in the list, and that dopamine is involved in glycemic control.

acetone: this is probably getting highly ranked because it will be a commonly occuring term with ketoacidosis (which causes the breath to smell of acetone).

phenobarbital: https://www.ncbi.nlm.nih.gov/pubmed/26348778  Phenobarbital reduces blood glucose and glucogenesis.

paracetamol: acetemenaphen / tylenol

benzene: carcinogenic.. https://academic.oup.com/toxsci/advance-article-abstract/doi/10.1093/toxsci/kfy252/5140220 Benzene exposure leads to insulin resistance in mice

caffeine: caffeine seems to affect glucose levels, probably badly in diabetics.

chlorpyrifos: an insecticide, exposure to which might be associated with diabetes

toluene: methylbenzene, used as a solvent

haloperidol: antipsychotic, tends to increase glucose level