
disease_ids = ["DOID:2841", 
            "DOID:9352",
            "DOID:14330",
            "DOID:1936",
            "DOID:10652",
            "DOID:0050427",
            "DOID:13636",
            "DOID:3302",
            "DOID:0050946",
            "DOID:0110858",
            "DOID:9562",
            "DOID:0050524",
            "DOID:3087",
            "DOID:8566",
            "DOID:8622",
            "DOID:1508",
            "DOID:12128",
            "DOID:0080234"]

disease_names = ["Asthma",
                "T2Diabetes",
                "Parkinson",
                "atherosclerosis",
                "Alzheimers",
                "XP",
                "FA",
                "Chordoma",
                "ARSACS",
                "PKD",
                "PCD",
                "MODY",
                "gingivitis",
                "HSV",
                "Measles",
                "Candidiasis",
                "Pica",
                "Mental retardation, autosomal dominant 49 (MRD49)"]