from BioLink.biolink_client import BioLinkWrapper
from pprint import pprint
import pandas as pd


class OrthologTraversal(object):

    def __init__(self):
        self.blw =BioLinkWrapper()

    def ortholog_set_by_taxid(self, gene_set, taxon_name):
        orthos = self.blw.get_orthoglog_gene_set(gene_set=gene_set, orth_taxon_name=taxon_name)
        orthologs = []
        for ortho in orthos:
            for ortho_id in ortho['associations']:
                orthologs.append(self.blw.parse_association(input_id=ortho_id['subject']['id'],
                                                         input_label=ortho_id['subject']['label'],
                                                         association=ortho_id))
        return orthologs

    def single_gene_ortholog(self, gene, taxon_name):
        ortho = self.blw.gene2orthologs(gene_curie=gene, orth_taxon_name=taxon_name)
        orthologs = []
        for assoc in ortho['associations']:
            orthologs.append({
                'gene_id': gene,
                'orth_id': assoc['object']['id'],
                'orth_label': assoc['object']['label'],
            })
        return orthologs



thing = {'context': 'https://raw.githubusercontent.com/biolink/biolink-model/master/context.jsonld',
 'datetime': '2018-11-06 22:07:14',
 'id': 'https://rtx.ncats.io/api/rtx/v1/response/559',
 'message': '25 results found',
 'n_results': 25,
 'original_question_text': 'What monogentic conditions are most enriched for phenotypes shared with DOID:9352',
 'query_type_id': 'Q10001',
 'reasoner_id': 'RTX',
 'response_code': 'OK',
 'restated_question_text': 'What monogentic conditions are most enriched for phenotypes shared with type 2 diabetes mellitus',
 'result_list': [{'confidence': 0.9993358516965531,
   'essence': 'HEART DEFECTS, CONGENITAL, AND OTHER CONGENITAL ANOMALIES; HDCA',
   'id': 'https://rtx.ncats.io/api/rtx/v1/result/27409',
   'reasoner_id': 'RTX',
   'result_graph': {'edge_list': [{'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0011628',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'DOID:9352',
      'target_id': 'HP:0011628',
      'type': 'has_phenotype'}],
    'node_list': [{'description': 'A developmental defect of the pericardium with congenital onset.',
      'id': 'HP:0011628',
      'name': 'Congenital defect of the pericardium',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0011628'},
     {'description': 'None',
      'id': 'OMIM:600001',
      'name': 'HEART DEFECTS, CONGENITAL, AND OTHER CONGENITAL ANOMALIES; HDCA',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_600001'},
     {'description': 'A diabetes mellitus that involves high blood glucose resulting from cells fail to use insulin properly.',
      'id': 'DOID:9352',
      'name': 'type 2 diabetes mellitus',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/DOID_9352'}]},
   'result_type': 'individual query answer',
   'row_data': ['type 2 diabetes mellitus',
    'DOID:9352',
    'HEART DEFECTS, CONGENITAL, AND OTHER CONGENITAL ANOMALIES; HDCA',
    'OMIM:600001',
    '0.000664'],
   'text': 'The drug HEART DEFECTS, CONGENITAL, AND OTHER CONGENITAL ANOMALIES; HDCA is predicted to treat type 2 diabetes mellitus.'},
  {'confidence': 0.9993356982086107,
   'essence': 'DIABETES MELLITUS, PERMANENT NEONATAL; PNDM',
   'id': 'https://rtx.ncats.io/api/rtx/v1/result/27410',
   'reasoner_id': 'RTX',
   'result_graph': {'edge_list': [{'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0011466',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'DOID:9352',
      'target_id': 'HP:0011466',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:606176',
      'target_id': 'HP:0000857',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0000857',
      'type': 'has_phenotype'}],
    'node_list': [{'description': 'Absence or underdevelopment of the gallbladder.',
      'id': 'HP:0011466',
      'name': 'Aplasia/Hypoplasia of the gallbladder',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0011466'},
     {'description': 'None',
      'id': 'HP:0000857',
      'name': 'Neonatal insulin-dependent diabetes mellitus',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0000857'},
     {'description': "Neonatal diabetes mellitus (NDM), defined as insulin-requiring hyperglycemia within the first 3 months of life, is a rare entity, with an estimated incidence of 1 in 400,000 neonates ({16:Shield, 2000}). In about half of the neonates, diabetes is transient (see {601410}) and resolves at a median age of 3 months, whereas the rest have a permanent insulin-dependent form of diabetes (PNDM). In a significant number of patients with transient neonatal diabetes mellitus, type II diabetes (see {125853}) appears later in life ({1:Arthur et al., 1997}). PNDM is distinct from childhood-onset autoimmune diabetes mellitus type I (IDDM; {222100}).\n\n{11:Massa et al. (2005)} noted that the diagnostic time limit for PNDM has changed over the years, ranging from onset within 30 days of birth to 3 months of age. However, as patients with the clinical phenotype caused by mutation in the KCNJ11 gene have been identified with onset up to 6 months of age, {11:Massa et al. (2005)} suggested that the term 'permanent diabetes mellitus of infancy' (PDMI) replace PNDM as a more accurate description, and include those who present up to 6 months of age. The authors suggested that the new acronym be linked to the gene product (e.g., GCK-PDMI, KCNJ11-PDMI) to avoid confusion with patients with early-onset, autoimmune type I diabetes.\n\n{4:Colombo et al. (2008)} proposed that, because individuals with INS gene mutations may present with diabetes well beyond 6 months of age and cannot be distinguished from patients with type 1 diabetes except for the absence of type 1 diabetes autoantibodies, the term PNDM should be replaced with 'monogenic diabetes of infancy (MDI),' a broad definition including any form of diabetes, permanent or transient, with onset during the first years of life and caused by a single gene defect.",
      'id': 'OMIM:606176',
      'name': 'DIABETES MELLITUS, PERMANENT NEONATAL; PNDM',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_606176'},
     {'description': 'None',
      'id': 'OMIM:600001',
      'name': 'HEART DEFECTS, CONGENITAL, AND OTHER CONGENITAL ANOMALIES; HDCA',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_600001'},
     {'description': 'A diabetes mellitus that involves high blood glucose resulting from cells fail to use insulin properly.',
      'id': 'DOID:9352',
      'name': 'type 2 diabetes mellitus',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/DOID_9352'}]},
   'result_type': 'individual query answer',
   'row_data': ['type 2 diabetes mellitus',
    'DOID:9352',
    'DIABETES MELLITUS, PERMANENT NEONATAL; PNDM',
    'OMIM:606176',
    '0.000664'],
   'text': 'The drug DIABETES MELLITUS, PERMANENT NEONATAL; PNDM is predicted to treat type 2 diabetes mellitus.'},
  {'confidence': 0.9992400173178024,
   'essence': 'PANCREATIC AND CEREBELLAR AGENESIS; PACA',
   'id': 'https://rtx.ncats.io/api/rtx/v1/result/27411',
   'reasoner_id': 'RTX',
   'result_graph': {'edge_list': [{'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0011466',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'DOID:9352',
      'target_id': 'HP:0011466',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:609069',
      'target_id': 'HP:0000857',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0000857',
      'type': 'has_phenotype'}],
    'node_list': [{'description': 'Absence or underdevelopment of the gallbladder.',
      'id': 'HP:0011466',
      'name': 'Aplasia/Hypoplasia of the gallbladder',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0011466'},
     {'description': 'None',
      'id': 'HP:0000857',
      'name': 'Neonatal insulin-dependent diabetes mellitus',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0000857'},
     {'description': 'None',
      'id': 'OMIM:609069',
      'name': 'PANCREATIC AND CEREBELLAR AGENESIS; PACA',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_609069'},
     {'description': 'None',
      'id': 'OMIM:600001',
      'name': 'HEART DEFECTS, CONGENITAL, AND OTHER CONGENITAL ANOMALIES; HDCA',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_600001'},
     {'description': 'A diabetes mellitus that involves high blood glucose resulting from cells fail to use insulin properly.',
      'id': 'DOID:9352',
      'name': 'type 2 diabetes mellitus',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/DOID_9352'}]},
   'result_type': 'individual query answer',
   'row_data': ['type 2 diabetes mellitus',
    'DOID:9352',
    'PANCREATIC AND CEREBELLAR AGENESIS; PACA',
    'OMIM:609069',
    '0.000760'],
   'text': 'The drug PANCREATIC AND CEREBELLAR AGENESIS; PACA is predicted to treat type 2 diabetes mellitus.'},
  {'confidence': 0.9991441843602131,
   'essence': 'MATURITY-ONSET DIABETES OF THE YOUNG; MODY',
   'id': 'https://rtx.ncats.io/api/rtx/v1/result/27412',
   'reasoner_id': 'RTX',
   'result_graph': {'edge_list': [{'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0011466',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'DOID:9352',
      'target_id': 'HP:0011466',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0000857',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:609069',
      'target_id': 'HP:0100800',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:606391',
      'target_id': 'HP:0100800',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:609069',
      'target_id': 'HP:0000857',
      'type': 'has_phenotype'}],
    'node_list': [{'description': 'Absence or underdevelopment of the gallbladder.',
      'id': 'HP:0011466',
      'name': 'Aplasia/Hypoplasia of the gallbladder',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0011466'},
     {'description': 'None',
      'id': 'OMIM:600001',
      'name': 'HEART DEFECTS, CONGENITAL, AND OTHER CONGENITAL ANOMALIES; HDCA',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_600001'},
     {'description': 'A congenital underdevelopment (aplasia or hypoplasia) of the pancreas.',
      'id': 'HP:0100800',
      'name': 'Aplasia/Hypoplasia of the pancreas',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0100800'},
     {'description': 'None',
      'id': 'HP:0000857',
      'name': 'Neonatal insulin-dependent diabetes mellitus',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0000857'},
     {'description': 'None',
      'id': 'OMIM:609069',
      'name': 'PANCREATIC AND CEREBELLAR AGENESIS; PACA',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_609069'},
     {'description': 'Maturity-onset diabetes of the young is an autosomal dominant form of diabetes typically occurring before 25 years of age and caused by primary insulin secretion defects. Despite its low prevalence, MODY is not a single entity but represents genetic, metabolic, and clinical heterogeneity ({18:Vaxillaire and Froguel, 2008}).\n\n<Subhead> Genetic Heterogeneity of MODY\n\nMODY1 ({125850}) is caused by heterozygous mutation in the hepatocyte nuclear factor-4-alpha gene (HNF4A; {600281}) on chromosome 20.\n\nMODY2 ({125851}) is caused by heterozygous mutation in the glucokinase gene (GCK; {138079}) on chromosome 7.\n\nMODY3 ({600496}) is caused by heterozygous mutation in the hepatocyte nuclear factor-1alpha gene (HNF1A; {142410}) on chromosome 12q24.2.\n\nMODY4 ({606392}) is caused by heterozygous mutation in the pancreas/duodenum homeobox protein-1 gene (PDX1; {600733}) on chromosome 13q12.1.\n\nMODY5 ({137920}) is caused by heterozygous mutation in the gene encoding hepatic transcription factor-2 (TCF2; {189907}) on chromosome 17cen-q21.3.\n\nMODY6 ({606394}) is caused by heterozygous mutation in the NEUROD1 gene ({601724}) on chromosome 2q32.\n\nMODY7 ({610508}) is caused by heterozygous mutation in the KLF11 gene ({603301}) on chromosome 2p25.\n\nMODY8 ({609812}), or diabetes-pancreatic exocrine dysfunction syndrome, is caused by heterozygous mutation in the CEL gene ({114840}) on chromosome 9q34.\n\nMODY9 ({612225}) is caused by heterozygous mutation in the PAX4 gene ({167413}) on chromosome 7q32.\n\nMODY10 ({613370}) is caused by heterozygous mutation in the insulin gene (INS; {176730}) on chromosome 11p15.5.\n\nMODY11 ({613375}) is caused by heterozygous mutation in the BLK gene ({191305}) on chromosome 8p23.\n\nMODY13 ({616329}) is caused by heterozygous mutation in the KCNJ11 gene ({600937}) on chromosome 11p15.\n\nMODY14 ({616511}) is caused by heterozygous mutation in the APPL1 gene ({604299}) on chromosome 3p14.',
      'id': 'OMIM:606391',
      'name': 'MATURITY-ONSET DIABETES OF THE YOUNG; MODY',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_606391'},
     {'description': 'A diabetes mellitus that involves high blood glucose resulting from cells fail to use insulin properly.',
      'id': 'DOID:9352',
      'name': 'type 2 diabetes mellitus',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/DOID_9352'}]},
   'result_type': 'individual query answer',
   'row_data': ['type 2 diabetes mellitus',
    'DOID:9352',
    'MATURITY-ONSET DIABETES OF THE YOUNG; MODY',
    'OMIM:606391',
    '0.000856'],
   'text': 'The drug MATURITY-ONSET DIABETES OF THE YOUNG; MODY is predicted to treat type 2 diabetes mellitus.'},
  {'confidence': 0.9991441755557792,
   'essence': 'RENAL CYSTS AND DIABETES SYNDROME; RCAD',
   'id': 'https://rtx.ncats.io/api/rtx/v1/result/27413',
   'reasoner_id': 'RTX',
   'result_graph': {'edge_list': [{'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0011466',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'DOID:9352',
      'target_id': 'HP:0011466',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:137920',
      'target_id': 'HP:0100800',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0000857',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:609069',
      'target_id': 'HP:0100800',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:609069',
      'target_id': 'HP:0000857',
      'type': 'has_phenotype'}],
    'node_list': [{'description': 'Absence or underdevelopment of the gallbladder.',
      'id': 'HP:0011466',
      'name': 'Aplasia/Hypoplasia of the gallbladder',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0011466'},
     {'description': "The 'renal cysts and diabetes syndrome' is an autosomal dominant disorder comprising (1) nondiabetic renal disease resulting from abnormal renal development, and (2) diabetes, which in some cases occurs earlier than age 25 years and is thus consistent with a diagnosis of maturity-onset diabetes of the young (MODY). The renal disease is highly variable and includes renal cysts, glomerular tufts, aberrant nephrogenesis, primitive tubules, irregular collecting systems, oligomeganephronia, enlarged renal pelvises, abnormal calyces, small kidney, single kidney, horseshoe kidney, and hyperuricemic nephropathy. Affected individuals may also have abnormalities of the genital tract, including vaginal aplasia, rudimentary uterus, bicornuate uterus, epididymal cysts, and atresia of the vas deferens ({3:Bingham et al., 2001}; {7:Fajans et al., 2001}; {1:Bellanne-Chantelot et al., 2004}; {6:Edghill et al., 2006}).\n\nThe renal abnormalities seen in the RCAD syndrome are part of a spectrum of malformations known as congenital anomalies of the kidney and urinary tract (CAKUT; see {610805}) (summary by {14:Nakayama et al., 2010}).",
      'id': 'OMIM:137920',
      'name': 'RENAL CYSTS AND DIABETES SYNDROME; RCAD',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_137920'},
     {'description': 'None',
      'id': 'OMIM:600001',
      'name': 'HEART DEFECTS, CONGENITAL, AND OTHER CONGENITAL ANOMALIES; HDCA',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_600001'},
     {'description': 'A congenital underdevelopment (aplasia or hypoplasia) of the pancreas.',
      'id': 'HP:0100800',
      'name': 'Aplasia/Hypoplasia of the pancreas',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0100800'},
     {'description': 'None',
      'id': 'HP:0000857',
      'name': 'Neonatal insulin-dependent diabetes mellitus',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0000857'},
     {'description': 'None',
      'id': 'OMIM:609069',
      'name': 'PANCREATIC AND CEREBELLAR AGENESIS; PACA',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_609069'},
     {'description': 'A diabetes mellitus that involves high blood glucose resulting from cells fail to use insulin properly.',
      'id': 'DOID:9352',
      'name': 'type 2 diabetes mellitus',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/DOID_9352'}]},
   'result_type': 'individual query answer',
   'row_data': ['type 2 diabetes mellitus',
    'DOID:9352',
    'RENAL CYSTS AND DIABETES SYNDROME; RCAD',
    'OMIM:137920',
    '0.000856'],
   'text': 'The drug RENAL CYSTS AND DIABETES SYNDROME; RCAD is predicted to treat type 2 diabetes mellitus.'},
  {'confidence': 0.9986966617598843,
   'essence': 'LIPODYSTROPHY, FAMILIAL PARTIAL, TYPE 6; FPLD6',
   'id': 'https://rtx.ncats.io/api/rtx/v1/result/27414',
   'reasoner_id': 'RTX',
   'result_graph': {'edge_list': [{'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:615980',
      'target_id': 'HP:0030685',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'DOID:9352',
      'target_id': 'HP:0030685',
      'type': 'has_phenotype'}],
    'node_list': [{'description': 'A reduced circulating concentration of adiponectin, a 30-kDa complement C1-related protein that is the most abundant secreted protein expressed in adipose tissue.',
      'id': 'HP:0030685',
      'name': 'Decreased adiponectin level',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0030685'},
     {'description': 'Familial partial lipodystrophy-6 (FPLD6) is characterized by abnormal subcutaneous fat distribution, with variable excess accumulation of fat in the face, neck, shoulders, axillae, back, abdomen, and pubic region, and reduction in subcutaneous fat of the lower extremities. Progressive adult-onset myopathy is seen in some patients, and there is variable association with diabetes, hypertriglyceridemia, low high-density lipoprotein (HDL) cholesterol, and hepatic steatosis ({4:Zolotov et al., 2017}).',
      'id': 'OMIM:615980',
      'name': 'LIPODYSTROPHY, FAMILIAL PARTIAL, TYPE 6; FPLD6',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_615980'},
     {'description': 'A diabetes mellitus that involves high blood glucose resulting from cells fail to use insulin properly.',
      'id': 'DOID:9352',
      'name': 'type 2 diabetes mellitus',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/DOID_9352'}]},
   'result_type': 'individual query answer',
   'row_data': ['type 2 diabetes mellitus',
    'DOID:9352',
    'LIPODYSTROPHY, FAMILIAL PARTIAL, TYPE 6; FPLD6',
    'OMIM:615980',
    '0.001303'],
   'text': 'The drug LIPODYSTROPHY, FAMILIAL PARTIAL, TYPE 6; FPLD6 is predicted to treat type 2 diabetes mellitus.'},
  {'confidence': 0.9985349259304863,
   'essence': 'LIPODYSTROPHY, CONGENITAL GENERALIZED, TYPE 1; CGL1',
   'id': 'https://rtx.ncats.io/api/rtx/v1/result/27415',
   'reasoner_id': 'RTX',
   'result_graph': {'edge_list': [{'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:608594',
      'target_id': 'HP:0003716',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'DOID:9352',
      'target_id': 'HP:0003716',
      'type': 'has_phenotype'}],
    'node_list': [{'description': 'None',
      'id': 'HP:0003716',
      'name': 'Generalized muscular appearance from birth',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0003716'},
     {'description': 'A diabetes mellitus that involves high blood glucose resulting from cells fail to use insulin properly.',
      'id': 'DOID:9352',
      'name': 'type 2 diabetes mellitus',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/DOID_9352'},
     {'description': 'Congenital generalized lipodystrophy (CGL), or Berardinelli-Seip syndrome, is a rare autosomal recessive disease characterized by a near absence of adipose tissue from birth or early infancy and severe insulin resistance. Other clinical and biologic features include acanthosis nigricans, muscular hypertrophy, hepatomegaly, altered glucose tolerance or diabetes mellitus, and hypertriglyceridemia ({11:Garg, 2004}).\n\n<Subhead> Genetic Heterogeneity of Congenital Generalized Lipodystrophy\n\nCongenital generalized lipodystrophy type 2 ({269700}) is caused by mutation in the BSCL2 gene ({606158}). Congenital generalized lipodystrophy type 3 ({612526}) is caused by mutation in the CAV1 gene ({601047}). Congenital generalized lipodystrophy type 4 ({613327}) is caused by mutation in the PTRF gene ({603198}).',
      'id': 'OMIM:608594',
      'name': 'LIPODYSTROPHY, CONGENITAL GENERALIZED, TYPE 1; CGL1',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_608594'}]},
   'result_type': 'individual query answer',
   'row_data': ['type 2 diabetes mellitus',
    'DOID:9352',
    'LIPODYSTROPHY, CONGENITAL GENERALIZED, TYPE 1; CGL1',
    'OMIM:608594',
    '0.001465'],
   'text': 'The drug LIPODYSTROPHY, CONGENITAL GENERALIZED, TYPE 1; CGL1 is predicted to treat type 2 diabetes mellitus.'},
  {'confidence': 0.9984259773728061,
   'essence': 'LIPODYSTROPHY, CONGENITAL GENERALIZED, TYPE 2; CGL2',
   'id': 'https://rtx.ncats.io/api/rtx/v1/result/27416',
   'reasoner_id': 'RTX',
   'result_graph': {'edge_list': [{'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:269700',
      'target_id': 'HP:0003716',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'DOID:9352',
      'target_id': 'HP:0003716',
      'type': 'has_phenotype'}],
    'node_list': [{'description': 'Congenital generalized lipodystrophy (CGL), also known as Berardinelli-Seip syndrome, is an autosomal recessive disorder characterized by marked paucity of adipose tissue, extreme insulin resistance, hypertriglyceridemia, hepatic steatosis and early onset of diabetes ({5:Garg, 2004}).\n\nFor a general description and a discussion of genetic heterogeneity of congenital generalized lipodystrophy, see CGL1 ({608594}).',
      'id': 'OMIM:269700',
      'name': 'LIPODYSTROPHY, CONGENITAL GENERALIZED, TYPE 2; CGL2',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_269700'},
     {'description': 'None',
      'id': 'HP:0003716',
      'name': 'Generalized muscular appearance from birth',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0003716'},
     {'description': 'A diabetes mellitus that involves high blood glucose resulting from cells fail to use insulin properly.',
      'id': 'DOID:9352',
      'name': 'type 2 diabetes mellitus',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/DOID_9352'}]},
   'result_type': 'individual query answer',
   'row_data': ['type 2 diabetes mellitus',
    'DOID:9352',
    'LIPODYSTROPHY, CONGENITAL GENERALIZED, TYPE 2; CGL2',
    'OMIM:269700',
    '0.001574'],
   'text': 'The drug LIPODYSTROPHY, CONGENITAL GENERALIZED, TYPE 2; CGL2 is predicted to treat type 2 diabetes mellitus.'},
  {'confidence': 0.9974923605553018,
   'essence': 'LIPODYSTROPHY, FAMILIAL PARTIAL, TYPE 2; FPLD2',
   'id': 'https://rtx.ncats.io/api/rtx/v1/result/27417',
   'reasoner_id': 'RTX',
   'result_graph': {'edge_list': [{'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'DOID:9352',
      'target_id': 'HP:0000287',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:151660',
      'target_id': 'HP:0000287',
      'type': 'has_phenotype'}],
    'node_list': [{'description': 'An increased amount of subcutaneous fat tissue in the face.',
      'id': 'HP:0000287',
      'name': 'Increased facial adipose tissue',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0000287'},
     {'description': 'A diabetes mellitus that involves high blood glucose resulting from cells fail to use insulin properly.',
      'id': 'DOID:9352',
      'name': 'type 2 diabetes mellitus',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/DOID_9352'},
     {'description': 'Familial partial lipodystrophy is a metabolic disorder characterized by abnormal subcutaneous adipose tissue distribution beginning in late childhood or early adult life. Affected individuals gradually lose fat from the upper and lower extremities and the gluteal and truncal regions, resulting in a muscular appearance with prominent superficial veins. In some patients, adipose tissue accumulates on the face and neck, causing a double chin, fat neck, or cushingoid appearance. Metabolic abnormalities include insulin-resistant diabetes mellitus with acanthosis nigricans and hypertriglyceridemia; hirsutism and menstrual abnormalities occur infrequently. Familial partial lipodystrophy may also be referred to as lipoatrophic diabetes mellitus, but the essential feature is loss of subcutaneous fat (review by {11:Garg, 2004}).\n\nThe disorder may be misdiagnosed as Cushing disease (see {219080}) ({16:Kobberling and Dunnigan, 1986}; {11:Garg, 2004}).\n\n<Subhead> Genetic Heterogeneity of Familial Partial Lipodystrophy\n\nFamilial partial lipodystrophy is a clinically and genetically heterogeneous disorder. Types 1 and 2 were originally described as clinical subtypes: type 1 (FPLD1; {608600}), characterized by loss of subcutaneous fat confined to the limbs ({17:Kobberling et al., 1975}), and FPLD2, characterized by loss of subcutaneous fat from the limbs and trunk ({7:Dunnigan et al., 1974}; {16:Kobberling and Dunnigan, 1986}). No genetic basis for FPLD1 has yet been delineated. FPLD3 ({604367}) is caused by mutation in the PPARG gene ({601487}) on chromosome 3p25; FPLD4 ({613877}) is caused by mutation in the PLIN1 gene ({170290}) on chromosome 15q26; FPLD5 ({615238}) is caused by mutation in the CIDEC gene ({612120}) on chromosome 3p25; and FPLD6 ({615980}) is caused by mutation in the LIPE gene ({151750}) on chromosome 19q13.',
      'id': 'OMIM:151660',
      'name': 'LIPODYSTROPHY, FAMILIAL PARTIAL, TYPE 2; FPLD2',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_151660'}]},
   'result_type': 'individual query answer',
   'row_data': ['type 2 diabetes mellitus',
    'DOID:9352',
    'LIPODYSTROPHY, FAMILIAL PARTIAL, TYPE 2; FPLD2',
    'OMIM:151660',
    '0.002508'],
   'text': 'The drug LIPODYSTROPHY, FAMILIAL PARTIAL, TYPE 2; FPLD2 is predicted to treat type 2 diabetes mellitus.'},
  {'confidence': 0.9974691309823895,
   'essence': 'MANDIBULOACRAL DYSPLASIA WITH TYPE A LIPODYSTROPHY; MADA',
   'id': 'https://rtx.ncats.io/api/rtx/v1/result/27418',
   'reasoner_id': 'RTX',
   'result_graph': {'edge_list': [{'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:248370',
      'target_id': 'HP:0001870',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'DOID:9352',
      'target_id': 'HP:0001870',
      'type': 'has_phenotype'}],
    'node_list': [{'description': 'Mandibuloacral dysplasia with type A lipodystrophy (MADA) is an autosomal recessive disorder characterized by growth retardation, craniofacial anomalies with mandibular hypoplasia, skeletal abnormalities with progressive osteolysis of the distal phalanges and clavicles, and pigmentary skin changes. The lipodystrophy is characterized by a marked acral loss of fatty tissue with normal or increased fatty tissue in the neck and trunk. Some patients may show progeroid features. Metabolic complications can arise due to insulin resistance and diabetes ({37:Young et al., 1971}; {30:Simha and Garg, 2002}; summary by {11:Garavelli et al., 2009}).\n\nSee also MAD type B (MADB; {608612}), which is caused by mutation in the ZMPSTE24 gene ({606480}).',
      'id': 'OMIM:248370',
      'name': 'MANDIBULOACRAL DYSPLASIA WITH TYPE A LIPODYSTROPHY; MADA',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_248370'},
     {'description': 'None',
      'id': 'HP:0001870',
      'name': 'Acroosteolysis of distal phalanges (feet)',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0001870'},
     {'description': 'A diabetes mellitus that involves high blood glucose resulting from cells fail to use insulin properly.',
      'id': 'DOID:9352',
      'name': 'type 2 diabetes mellitus',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/DOID_9352'}]},
   'result_type': 'individual query answer',
   'row_data': ['type 2 diabetes mellitus',
    'DOID:9352',
    'MANDIBULOACRAL DYSPLASIA WITH TYPE A LIPODYSTROPHY; MADA',
    'OMIM:248370',
    '0.002531'],
   'text': 'The drug MANDIBULOACRAL DYSPLASIA WITH TYPE A LIPODYSTROPHY; MADA is predicted to treat type 2 diabetes mellitus.'},
  {'confidence': 0.9967023125198323,
   'essence': 'LIPODYSTROPHY, FAMILIAL PARTIAL, TYPE 5; FPLD5',
   'id': 'https://rtx.ncats.io/api/rtx/v1/result/27419',
   'reasoner_id': 'RTX',
   'result_graph': {'edge_list': [{'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:615238',
      'target_id': 'HP:0030685',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'DOID:9352',
      'target_id': 'HP:0030685',
      'type': 'has_phenotype'}],
    'node_list': [{'description': 'A reduced circulating concentration of adiponectin, a 30-kDa complement C1-related protein that is the most abundant secreted protein expressed in adipose tissue.',
      'id': 'HP:0030685',
      'name': 'Decreased adiponectin level',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0030685'},
     {'description': 'None',
      'id': 'OMIM:615238',
      'name': 'LIPODYSTROPHY, FAMILIAL PARTIAL, TYPE 5; FPLD5',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_615238'},
     {'description': 'A diabetes mellitus that involves high blood glucose resulting from cells fail to use insulin properly.',
      'id': 'DOID:9352',
      'name': 'type 2 diabetes mellitus',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/DOID_9352'}]},
   'result_type': 'individual query answer',
   'row_data': ['type 2 diabetes mellitus',
    'DOID:9352',
    'LIPODYSTROPHY, FAMILIAL PARTIAL, TYPE 5; FPLD5',
    'OMIM:615238',
    '0.003298'],
   'text': 'The drug LIPODYSTROPHY, FAMILIAL PARTIAL, TYPE 5; FPLD5 is predicted to treat type 2 diabetes mellitus.'},
  {'confidence': 0.9868371352781745,
   'essence': 'HYPOTHYROIDISM, CENTRAL, AND TESTICULAR ENLARGEMENT; CHTE',
   'id': 'https://rtx.ncats.io/api/rtx/v1/result/27420',
   'reasoner_id': 'RTX',
   'result_graph': {'edge_list': [{'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0011466',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'DOID:9352',
      'target_id': 'HP:0011466',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:606391',
      'target_id': 'HP:0025502',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:300888',
      'target_id': 'HP:0025502',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0000857',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:609069',
      'target_id': 'HP:0100800',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:606391',
      'target_id': 'HP:0100800',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:609069',
      'target_id': 'HP:0000857',
      'type': 'has_phenotype'}],
    'node_list': [{'description': 'Absence or underdevelopment of the gallbladder.',
      'id': 'HP:0011466',
      'name': 'Aplasia/Hypoplasia of the gallbladder',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0011466'},
     {'description': 'Increased body weight with a body mass index of 25-29.9 kg per square meter.',
      'id': 'HP:0025502',
      'name': 'Overweight',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0025502'},
     {'description': 'None',
      'id': 'OMIM:600001',
      'name': 'HEART DEFECTS, CONGENITAL, AND OTHER CONGENITAL ANOMALIES; HDCA',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_600001'},
     {'description': 'A congenital underdevelopment (aplasia or hypoplasia) of the pancreas.',
      'id': 'HP:0100800',
      'name': 'Aplasia/Hypoplasia of the pancreas',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0100800'},
     {'description': 'None',
      'id': 'HP:0000857',
      'name': 'Neonatal insulin-dependent diabetes mellitus',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0000857'},
     {'description': 'None',
      'id': 'OMIM:609069',
      'name': 'PANCREATIC AND CEREBELLAR AGENESIS; PACA',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_609069'},
     {'description': 'Maturity-onset diabetes of the young is an autosomal dominant form of diabetes typically occurring before 25 years of age and caused by primary insulin secretion defects. Despite its low prevalence, MODY is not a single entity but represents genetic, metabolic, and clinical heterogeneity ({18:Vaxillaire and Froguel, 2008}).\n\n<Subhead> Genetic Heterogeneity of MODY\n\nMODY1 ({125850}) is caused by heterozygous mutation in the hepatocyte nuclear factor-4-alpha gene (HNF4A; {600281}) on chromosome 20.\n\nMODY2 ({125851}) is caused by heterozygous mutation in the glucokinase gene (GCK; {138079}) on chromosome 7.\n\nMODY3 ({600496}) is caused by heterozygous mutation in the hepatocyte nuclear factor-1alpha gene (HNF1A; {142410}) on chromosome 12q24.2.\n\nMODY4 ({606392}) is caused by heterozygous mutation in the pancreas/duodenum homeobox protein-1 gene (PDX1; {600733}) on chromosome 13q12.1.\n\nMODY5 ({137920}) is caused by heterozygous mutation in the gene encoding hepatic transcription factor-2 (TCF2; {189907}) on chromosome 17cen-q21.3.\n\nMODY6 ({606394}) is caused by heterozygous mutation in the NEUROD1 gene ({601724}) on chromosome 2q32.\n\nMODY7 ({610508}) is caused by heterozygous mutation in the KLF11 gene ({603301}) on chromosome 2p25.\n\nMODY8 ({609812}), or diabetes-pancreatic exocrine dysfunction syndrome, is caused by heterozygous mutation in the CEL gene ({114840}) on chromosome 9q34.\n\nMODY9 ({612225}) is caused by heterozygous mutation in the PAX4 gene ({167413}) on chromosome 7q32.\n\nMODY10 ({613370}) is caused by heterozygous mutation in the insulin gene (INS; {176730}) on chromosome 11p15.5.\n\nMODY11 ({613375}) is caused by heterozygous mutation in the BLK gene ({191305}) on chromosome 8p23.\n\nMODY13 ({616329}) is caused by heterozygous mutation in the KCNJ11 gene ({600937}) on chromosome 11p15.\n\nMODY14 ({616511}) is caused by heterozygous mutation in the APPL1 gene ({604299}) on chromosome 3p14.',
      'id': 'OMIM:606391',
      'name': 'MATURITY-ONSET DIABETES OF THE YOUNG; MODY',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_606391'},
     {'description': 'A diabetes mellitus that involves high blood glucose resulting from cells fail to use insulin properly.',
      'id': 'DOID:9352',
      'name': 'type 2 diabetes mellitus',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/DOID_9352'},
     {'description': 'None',
      'id': 'OMIM:300888',
      'name': 'HYPOTHYROIDISM, CENTRAL, AND TESTICULAR ENLARGEMENT; CHTE',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_300888'}]},
   'result_type': 'individual query answer',
   'row_data': ['type 2 diabetes mellitus',
    'DOID:9352',
    'HYPOTHYROIDISM, CENTRAL, AND TESTICULAR ENLARGEMENT; CHTE',
    'OMIM:300888',
    '0.013163'],
   'text': 'The drug HYPOTHYROIDISM, CENTRAL, AND TESTICULAR ENLARGEMENT; CHTE is predicted to treat type 2 diabetes mellitus.'},
  {'confidence': 0.9866711879198685,
   'essence': 'HYPOBETALIPOPROTEINEMIA, FAMILIAL, 2; FHBL2',
   'id': 'https://rtx.ncats.io/api/rtx/v1/result/27421',
   'reasoner_id': 'RTX',
   'result_graph': {'edge_list': [{'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:605019',
      'target_id': 'HP:0012153',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'DOID:9352',
      'target_id': 'HP:0012153',
      'type': 'has_phenotype'}],
    'node_list': [{'description': 'An decrease in the level of triglycerides in the blood.',
      'id': 'HP:0012153',
      'name': 'Hypotriglyceridemia',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0012153'},
     {'description': 'Hypobetalipoproteinemia (HBL) is defined as permanently low levels, below the 5th percentile of sex- and age-matched individuals in the population, of apolipoprotein B (apoB), total cholesterol, and low-density lipoprotein (LDL) cholesterol; the lipid profile in FHBL2 includes low HDL cholesterol as well. HBL can result from environmental factors such as a strict vegetarian diet, or can be secondary to certain diseases such as intestinal fat malabsorption, chronic pancreatitis, severe liver disease, malnutrition, or hyperthyroidism. Heritable primary causes of HBL include chylomicron retention disease (CMRD; {246700}), abetalipoproteinemia ({200100}), and familial hypobetalipoproteinemia (FHBL) (summary by {2:Martin-Campos et al., 2012}).\n\nFor a discussion of genetic heterogeneity of familial hypobetalipoproteinemia, see FHBL1 ({615558}).',
      'id': 'OMIM:605019',
      'name': 'HYPOBETALIPOPROTEINEMIA, FAMILIAL, 2; FHBL2',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_605019'},
     {'description': 'A diabetes mellitus that involves high blood glucose resulting from cells fail to use insulin properly.',
      'id': 'DOID:9352',
      'name': 'type 2 diabetes mellitus',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/DOID_9352'}]},
   'result_type': 'individual query answer',
   'row_data': ['type 2 diabetes mellitus',
    'DOID:9352',
    'HYPOBETALIPOPROTEINEMIA, FAMILIAL, 2; FHBL2',
    'OMIM:605019',
    '0.013329'],
   'text': 'The drug HYPOBETALIPOPROTEINEMIA, FAMILIAL, 2; FHBL2 is predicted to treat type 2 diabetes mellitus.'},
  {'confidence': 0.9827678663616679,
   'essence': 'MATURITY-ONSET DIABETES OF THE YOUNG, TYPE 8, WITH EXOCRINE DYSFUNCTION; MODY8',
   'id': 'https://rtx.ncats.io/api/rtx/v1/result/27422',
   'reasoner_id': 'RTX',
   'result_graph': {'edge_list': [{'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0011466',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'DOID:9352',
      'target_id': 'HP:0011466',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:606391',
      'target_id': 'HP:0012092',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:609812',
      'target_id': 'HP:0012092',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0000857',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:609069',
      'target_id': 'HP:0100800',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:606391',
      'target_id': 'HP:0100800',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:609069',
      'target_id': 'HP:0000857',
      'type': 'has_phenotype'}],
    'node_list': [{'description': 'Absence or underdevelopment of the gallbladder.',
      'id': 'HP:0011466',
      'name': 'Aplasia/Hypoplasia of the gallbladder',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0011466'},
     {'description': 'A functional anomaly of the acinar gland portion of the pancreas that secretes digestive enzymes.',
      'id': 'HP:0012092',
      'name': 'Abnormality of exocrine pancreas physiology',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0012092'},
     {'description': 'None',
      'id': 'OMIM:600001',
      'name': 'HEART DEFECTS, CONGENITAL, AND OTHER CONGENITAL ANOMALIES; HDCA',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_600001'},
     {'description': 'A congenital underdevelopment (aplasia or hypoplasia) of the pancreas.',
      'id': 'HP:0100800',
      'name': 'Aplasia/Hypoplasia of the pancreas',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0100800'},
     {'description': 'None',
      'id': 'HP:0000857',
      'name': 'Neonatal insulin-dependent diabetes mellitus',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0000857'},
     {'description': 'None',
      'id': 'OMIM:609069',
      'name': 'PANCREATIC AND CEREBELLAR AGENESIS; PACA',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_609069'},
     {'description': 'Maturity-onset diabetes of the young is an autosomal dominant form of diabetes typically occurring before 25 years of age and caused by primary insulin secretion defects. Despite its low prevalence, MODY is not a single entity but represents genetic, metabolic, and clinical heterogeneity ({18:Vaxillaire and Froguel, 2008}).\n\n<Subhead> Genetic Heterogeneity of MODY\n\nMODY1 ({125850}) is caused by heterozygous mutation in the hepatocyte nuclear factor-4-alpha gene (HNF4A; {600281}) on chromosome 20.\n\nMODY2 ({125851}) is caused by heterozygous mutation in the glucokinase gene (GCK; {138079}) on chromosome 7.\n\nMODY3 ({600496}) is caused by heterozygous mutation in the hepatocyte nuclear factor-1alpha gene (HNF1A; {142410}) on chromosome 12q24.2.\n\nMODY4 ({606392}) is caused by heterozygous mutation in the pancreas/duodenum homeobox protein-1 gene (PDX1; {600733}) on chromosome 13q12.1.\n\nMODY5 ({137920}) is caused by heterozygous mutation in the gene encoding hepatic transcription factor-2 (TCF2; {189907}) on chromosome 17cen-q21.3.\n\nMODY6 ({606394}) is caused by heterozygous mutation in the NEUROD1 gene ({601724}) on chromosome 2q32.\n\nMODY7 ({610508}) is caused by heterozygous mutation in the KLF11 gene ({603301}) on chromosome 2p25.\n\nMODY8 ({609812}), or diabetes-pancreatic exocrine dysfunction syndrome, is caused by heterozygous mutation in the CEL gene ({114840}) on chromosome 9q34.\n\nMODY9 ({612225}) is caused by heterozygous mutation in the PAX4 gene ({167413}) on chromosome 7q32.\n\nMODY10 ({613370}) is caused by heterozygous mutation in the insulin gene (INS; {176730}) on chromosome 11p15.5.\n\nMODY11 ({613375}) is caused by heterozygous mutation in the BLK gene ({191305}) on chromosome 8p23.\n\nMODY13 ({616329}) is caused by heterozygous mutation in the KCNJ11 gene ({600937}) on chromosome 11p15.\n\nMODY14 ({616511}) is caused by heterozygous mutation in the APPL1 gene ({604299}) on chromosome 3p14.',
      'id': 'OMIM:606391',
      'name': 'MATURITY-ONSET DIABETES OF THE YOUNG; MODY',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_606391'},
     {'description': 'A diabetes mellitus that involves high blood glucose resulting from cells fail to use insulin properly.',
      'id': 'DOID:9352',
      'name': 'type 2 diabetes mellitus',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/DOID_9352'},
     {'description': 'None',
      'id': 'OMIM:609812',
      'name': 'MATURITY-ONSET DIABETES OF THE YOUNG, TYPE 8, WITH EXOCRINE DYSFUNCTION; MODY8',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_609812'}]},
   'result_type': 'individual query answer',
   'row_data': ['type 2 diabetes mellitus',
    'DOID:9352',
    'MATURITY-ONSET DIABETES OF THE YOUNG, TYPE 8, WITH EXOCRINE DYSFUNCTION; MODY8',
    'OMIM:609812',
    '0.017232'],
   'text': 'The drug MATURITY-ONSET DIABETES OF THE YOUNG, TYPE 8, WITH EXOCRINE DYSFUNCTION; MODY8 is predicted to treat type 2 diabetes mellitus.'},
  {'confidence': 0.9827678663616679,
   'essence': 'MATURITY-ONSET DIABETES OF THE YOUNG, TYPE 11; MODY11',
   'id': 'https://rtx.ncats.io/api/rtx/v1/result/27423',
   'reasoner_id': 'RTX',
   'result_graph': {'edge_list': [{'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0011466',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'DOID:9352',
      'target_id': 'HP:0011466',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:606391',
      'target_id': 'HP:0025502',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:613375',
      'target_id': 'HP:0025502',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0000857',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:609069',
      'target_id': 'HP:0100800',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:606391',
      'target_id': 'HP:0100800',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:609069',
      'target_id': 'HP:0000857',
      'type': 'has_phenotype'}],
    'node_list': [{'description': 'Absence or underdevelopment of the gallbladder.',
      'id': 'HP:0011466',
      'name': 'Aplasia/Hypoplasia of the gallbladder',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0011466'},
     {'description': 'Increased body weight with a body mass index of 25-29.9 kg per square meter.',
      'id': 'HP:0025502',
      'name': 'Overweight',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0025502'},
     {'description': 'None',
      'id': 'OMIM:600001',
      'name': 'HEART DEFECTS, CONGENITAL, AND OTHER CONGENITAL ANOMALIES; HDCA',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_600001'},
     {'description': 'A congenital underdevelopment (aplasia or hypoplasia) of the pancreas.',
      'id': 'HP:0100800',
      'name': 'Aplasia/Hypoplasia of the pancreas',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0100800'},
     {'description': 'None',
      'id': 'HP:0000857',
      'name': 'Neonatal insulin-dependent diabetes mellitus',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0000857'},
     {'description': 'None',
      'id': 'OMIM:609069',
      'name': 'PANCREATIC AND CEREBELLAR AGENESIS; PACA',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_609069'},
     {'description': 'Maturity-onset diabetes of the young is an autosomal dominant form of diabetes typically occurring before 25 years of age and caused by primary insulin secretion defects. Despite its low prevalence, MODY is not a single entity but represents genetic, metabolic, and clinical heterogeneity ({18:Vaxillaire and Froguel, 2008}).\n\n<Subhead> Genetic Heterogeneity of MODY\n\nMODY1 ({125850}) is caused by heterozygous mutation in the hepatocyte nuclear factor-4-alpha gene (HNF4A; {600281}) on chromosome 20.\n\nMODY2 ({125851}) is caused by heterozygous mutation in the glucokinase gene (GCK; {138079}) on chromosome 7.\n\nMODY3 ({600496}) is caused by heterozygous mutation in the hepatocyte nuclear factor-1alpha gene (HNF1A; {142410}) on chromosome 12q24.2.\n\nMODY4 ({606392}) is caused by heterozygous mutation in the pancreas/duodenum homeobox protein-1 gene (PDX1; {600733}) on chromosome 13q12.1.\n\nMODY5 ({137920}) is caused by heterozygous mutation in the gene encoding hepatic transcription factor-2 (TCF2; {189907}) on chromosome 17cen-q21.3.\n\nMODY6 ({606394}) is caused by heterozygous mutation in the NEUROD1 gene ({601724}) on chromosome 2q32.\n\nMODY7 ({610508}) is caused by heterozygous mutation in the KLF11 gene ({603301}) on chromosome 2p25.\n\nMODY8 ({609812}), or diabetes-pancreatic exocrine dysfunction syndrome, is caused by heterozygous mutation in the CEL gene ({114840}) on chromosome 9q34.\n\nMODY9 ({612225}) is caused by heterozygous mutation in the PAX4 gene ({167413}) on chromosome 7q32.\n\nMODY10 ({613370}) is caused by heterozygous mutation in the insulin gene (INS; {176730}) on chromosome 11p15.5.\n\nMODY11 ({613375}) is caused by heterozygous mutation in the BLK gene ({191305}) on chromosome 8p23.\n\nMODY13 ({616329}) is caused by heterozygous mutation in the KCNJ11 gene ({600937}) on chromosome 11p15.\n\nMODY14 ({616511}) is caused by heterozygous mutation in the APPL1 gene ({604299}) on chromosome 3p14.',
      'id': 'OMIM:606391',
      'name': 'MATURITY-ONSET DIABETES OF THE YOUNG; MODY',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_606391'},
     {'description': 'A diabetes mellitus that involves high blood glucose resulting from cells fail to use insulin properly.',
      'id': 'DOID:9352',
      'name': 'type 2 diabetes mellitus',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/DOID_9352'},
     {'description': 'None',
      'id': 'OMIM:613375',
      'name': 'MATURITY-ONSET DIABETES OF THE YOUNG, TYPE 11; MODY11',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_613375'}]},
   'result_type': 'individual query answer',
   'row_data': ['type 2 diabetes mellitus',
    'DOID:9352',
    'MATURITY-ONSET DIABETES OF THE YOUNG, TYPE 11; MODY11',
    'OMIM:613375',
    '0.017232'],
   'text': 'The drug MATURITY-ONSET DIABETES OF THE YOUNG, TYPE 11; MODY11 is predicted to treat type 2 diabetes mellitus.'},
  {'confidence': 0.9826019190033619,
   'essence': 'APOLIPOPROTEIN C-III DEFICIENCY',
   'id': 'https://rtx.ncats.io/api/rtx/v1/result/27424',
   'reasoner_id': 'RTX',
   'result_graph': {'edge_list': [{'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:614028',
      'target_id': 'HP:0012153',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'DOID:9352',
      'target_id': 'HP:0012153',
      'type': 'has_phenotype'}],
    'node_list': [{'description': 'An decrease in the level of triglycerides in the blood.',
      'id': 'HP:0012153',
      'name': 'Hypotriglyceridemia',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0012153'},
     {'description': 'None',
      'id': 'OMIM:614028',
      'name': 'APOLIPOPROTEIN C-III DEFICIENCY',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_614028'},
     {'description': 'A diabetes mellitus that involves high blood glucose resulting from cells fail to use insulin properly.',
      'id': 'DOID:9352',
      'name': 'type 2 diabetes mellitus',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/DOID_9352'}]},
   'result_type': 'individual query answer',
   'row_data': ['type 2 diabetes mellitus',
    'DOID:9352',
    'APOLIPOPROTEIN C-III DEFICIENCY',
    'OMIM:614028',
    '0.017398'],
   'text': 'The drug APOLIPOPROTEIN C-III DEFICIENCY is predicted to treat type 2 diabetes mellitus.'},
  {'confidence': 0.9821421253996223,
   'essence': 'OSTEOPETROSIS, AUTOSOMAL RECESSIVE 6; OPTB6',
   'id': 'https://rtx.ncats.io/api/rtx/v1/result/27425',
   'reasoner_id': 'RTX',
   'result_graph': {'edge_list': [{'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'DOID:9352',
      'target_id': 'HP:0100959',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:611497',
      'target_id': 'HP:0100959',
      'type': 'has_phenotype'}],
    'node_list': [{'description': 'Dense radiopaque bands of bone which are thicker than the adjacent diaphyseal cortex and may form at the metaphysis of growing bones. They appear on radiographs as bone that is more radiopaque that the adjacent diaphyseal cortex.',
      'id': 'HP:0100959',
      'name': 'Dense metaphyseal bands',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0100959'},
     {'description': 'A diabetes mellitus that involves high blood glucose resulting from cells fail to use insulin properly.',
      'id': 'DOID:9352',
      'name': 'type 2 diabetes mellitus',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/DOID_9352'},
     {'description': 'None',
      'id': 'OMIM:611497',
      'name': 'OSTEOPETROSIS, AUTOSOMAL RECESSIVE 6; OPTB6',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_611497'}]},
   'result_type': 'individual query answer',
   'row_data': ['type 2 diabetes mellitus',
    'DOID:9352',
    'OSTEOPETROSIS, AUTOSOMAL RECESSIVE 6; OPTB6',
    'OMIM:611497',
    '0.017858'],
   'text': 'The drug OSTEOPETROSIS, AUTOSOMAL RECESSIVE 6; OPTB6 is predicted to treat type 2 diabetes mellitus.'},
  {'confidence': 0.9789063916868372,
   'essence': 'DIABETES MELLITUS, TRANSIENT NEONATAL, 3',
   'id': 'https://rtx.ncats.io/api/rtx/v1/result/27426',
   'reasoner_id': 'RTX',
   'result_graph': {'edge_list': [{'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0011466',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'DOID:9352',
      'target_id': 'HP:0011466',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0000857',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:606176',
      'target_id': 'HP:0040217',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:610582',
      'target_id': 'HP:0040217',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:606176',
      'target_id': 'HP:0000857',
      'type': 'has_phenotype'}],
    'node_list': [{'description': 'Absence or underdevelopment of the gallbladder.',
      'id': 'HP:0011466',
      'name': 'Aplasia/Hypoplasia of the gallbladder',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0011466'},
     {'description': 'None',
      'id': 'OMIM:600001',
      'name': 'HEART DEFECTS, CONGENITAL, AND OTHER CONGENITAL ANOMALIES; HDCA',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_600001'},
     {'description': 'An increased concentration of hemoglobin A1c (HbA1c), which is the product of nonenzymatic attachment of a hexose molecule to the N-terminal amino acid of the hemoglobin molecule. This reaction is dependent on blood glucose concentration, and therefore reflects the mean glucose concentration over the previous 8 to 12 weeks. The HbA1c level provides a better indication of long-term glycemic control than one-time blood or urinary glucose measurements.',
      'id': 'HP:0040217',
      'name': 'Elevated hemoglobin A1c',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0040217'},
     {'description': 'None',
      'id': 'HP:0000857',
      'name': 'Neonatal insulin-dependent diabetes mellitus',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0000857'},
     {'description': "Neonatal diabetes mellitus (NDM), defined as insulin-requiring hyperglycemia within the first 3 months of life, is a rare entity, with an estimated incidence of 1 in 400,000 neonates ({16:Shield, 2000}). In about half of the neonates, diabetes is transient (see {601410}) and resolves at a median age of 3 months, whereas the rest have a permanent insulin-dependent form of diabetes (PNDM). In a significant number of patients with transient neonatal diabetes mellitus, type II diabetes (see {125853}) appears later in life ({1:Arthur et al., 1997}). PNDM is distinct from childhood-onset autoimmune diabetes mellitus type I (IDDM; {222100}).\n\n{11:Massa et al. (2005)} noted that the diagnostic time limit for PNDM has changed over the years, ranging from onset within 30 days of birth to 3 months of age. However, as patients with the clinical phenotype caused by mutation in the KCNJ11 gene have been identified with onset up to 6 months of age, {11:Massa et al. (2005)} suggested that the term 'permanent diabetes mellitus of infancy' (PDMI) replace PNDM as a more accurate description, and include those who present up to 6 months of age. The authors suggested that the new acronym be linked to the gene product (e.g., GCK-PDMI, KCNJ11-PDMI) to avoid confusion with patients with early-onset, autoimmune type I diabetes.\n\n{4:Colombo et al. (2008)} proposed that, because individuals with INS gene mutations may present with diabetes well beyond 6 months of age and cannot be distinguished from patients with type 1 diabetes except for the absence of type 1 diabetes autoantibodies, the term PNDM should be replaced with 'monogenic diabetes of infancy (MDI),' a broad definition including any form of diabetes, permanent or transient, with onset during the first years of life and caused by a single gene defect.",
      'id': 'OMIM:606176',
      'name': 'DIABETES MELLITUS, PERMANENT NEONATAL; PNDM',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_606176'},
     {'description': 'A diabetes mellitus that involves high blood glucose resulting from cells fail to use insulin properly.',
      'id': 'DOID:9352',
      'name': 'type 2 diabetes mellitus',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/DOID_9352'},
     {'description': 'None',
      'id': 'OMIM:610582',
      'name': 'DIABETES MELLITUS, TRANSIENT NEONATAL, 3',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_610582'}]},
   'result_type': 'individual query answer',
   'row_data': ['type 2 diabetes mellitus',
    'DOID:9352',
    'DIABETES MELLITUS, TRANSIENT NEONATAL, 3',
    'OMIM:610582',
    '0.021094'],
   'text': 'The drug DIABETES MELLITUS, TRANSIENT NEONATAL, 3 is predicted to treat type 2 diabetes mellitus.'},
  {'confidence': 0.9787150287736753,
   'essence': 'GLOMERULOCYSTIC KIDNEY DISEASE WITH HYPERURICEMIA AND ISOSTHENURIA',
   'id': 'https://rtx.ncats.io/api/rtx/v1/result/27427',
   'reasoner_id': 'RTX',
   'result_graph': {'edge_list': [{'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0011466',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'DOID:9352',
      'target_id': 'HP:0011466',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:609886',
      'target_id': 'HP:0100611',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:606391',
      'target_id': 'HP:0100611',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0000857',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:609069',
      'target_id': 'HP:0100800',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:606391',
      'target_id': 'HP:0100800',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:609069',
      'target_id': 'HP:0000857',
      'type': 'has_phenotype'}],
    'node_list': [{'description': 'Absence or underdevelopment of the gallbladder.',
      'id': 'HP:0011466',
      'name': 'Aplasia/Hypoplasia of the gallbladder',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0011466'},
     {'description': 'Glomerulocystic kidney disease is characterized by cystic dilatation of the Bowman space and the initial proximal convoluted tubule. Both sporadic and familial occurrences have been observed. {4:Sharp et al. (1997)} noted that GCKD had primarily been recognized in infants with a family history of classic, autosomal dominant polycystic kidney disease (PKD). However, dominantly transmitted GCKD associated with either hypoplastic or normal-sized kidneys has also been reported in older children and adults. Hypoplastic GCKD has been identified in some families with mutations in the TCF2 gene ({189907}) as part of the clinical phenotype of renal cysts and diabetes syndrome ({137920}).',
      'id': 'OMIM:609886',
      'name': 'GLOMERULOCYSTIC KIDNEY DISEASE WITH HYPERURICEMIA AND ISOSTHENURIA',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_609886'},
     {'description': "The presence of many cysts in the glomerulus of the kidney related to dilatation of the Bowman's capsule.",
      'id': 'HP:0100611',
      'name': 'Multiple glomerular cysts',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0100611'},
     {'description': 'None',
      'id': 'OMIM:600001',
      'name': 'HEART DEFECTS, CONGENITAL, AND OTHER CONGENITAL ANOMALIES; HDCA',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_600001'},
     {'description': 'A congenital underdevelopment (aplasia or hypoplasia) of the pancreas.',
      'id': 'HP:0100800',
      'name': 'Aplasia/Hypoplasia of the pancreas',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0100800'},
     {'description': 'None',
      'id': 'HP:0000857',
      'name': 'Neonatal insulin-dependent diabetes mellitus',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0000857'},
     {'description': 'None',
      'id': 'OMIM:609069',
      'name': 'PANCREATIC AND CEREBELLAR AGENESIS; PACA',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_609069'},
     {'description': 'Maturity-onset diabetes of the young is an autosomal dominant form of diabetes typically occurring before 25 years of age and caused by primary insulin secretion defects. Despite its low prevalence, MODY is not a single entity but represents genetic, metabolic, and clinical heterogeneity ({18:Vaxillaire and Froguel, 2008}).\n\n<Subhead> Genetic Heterogeneity of MODY\n\nMODY1 ({125850}) is caused by heterozygous mutation in the hepatocyte nuclear factor-4-alpha gene (HNF4A; {600281}) on chromosome 20.\n\nMODY2 ({125851}) is caused by heterozygous mutation in the glucokinase gene (GCK; {138079}) on chromosome 7.\n\nMODY3 ({600496}) is caused by heterozygous mutation in the hepatocyte nuclear factor-1alpha gene (HNF1A; {142410}) on chromosome 12q24.2.\n\nMODY4 ({606392}) is caused by heterozygous mutation in the pancreas/duodenum homeobox protein-1 gene (PDX1; {600733}) on chromosome 13q12.1.\n\nMODY5 ({137920}) is caused by heterozygous mutation in the gene encoding hepatic transcription factor-2 (TCF2; {189907}) on chromosome 17cen-q21.3.\n\nMODY6 ({606394}) is caused by heterozygous mutation in the NEUROD1 gene ({601724}) on chromosome 2q32.\n\nMODY7 ({610508}) is caused by heterozygous mutation in the KLF11 gene ({603301}) on chromosome 2p25.\n\nMODY8 ({609812}), or diabetes-pancreatic exocrine dysfunction syndrome, is caused by heterozygous mutation in the CEL gene ({114840}) on chromosome 9q34.\n\nMODY9 ({612225}) is caused by heterozygous mutation in the PAX4 gene ({167413}) on chromosome 7q32.\n\nMODY10 ({613370}) is caused by heterozygous mutation in the insulin gene (INS; {176730}) on chromosome 11p15.5.\n\nMODY11 ({613375}) is caused by heterozygous mutation in the BLK gene ({191305}) on chromosome 8p23.\n\nMODY13 ({616329}) is caused by heterozygous mutation in the KCNJ11 gene ({600937}) on chromosome 11p15.\n\nMODY14 ({616511}) is caused by heterozygous mutation in the APPL1 gene ({604299}) on chromosome 3p14.',
      'id': 'OMIM:606391',
      'name': 'MATURITY-ONSET DIABETES OF THE YOUNG; MODY',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_606391'},
     {'description': 'A diabetes mellitus that involves high blood glucose resulting from cells fail to use insulin properly.',
      'id': 'DOID:9352',
      'name': 'type 2 diabetes mellitus',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/DOID_9352'}]},
   'result_type': 'individual query answer',
   'row_data': ['type 2 diabetes mellitus',
    'DOID:9352',
    'GLOMERULOCYSTIC KIDNEY DISEASE WITH HYPERURICEMIA AND ISOSTHENURIA',
    'OMIM:609886',
    '0.021285'],
   'text': 'The drug GLOMERULOCYSTIC KIDNEY DISEASE WITH HYPERURICEMIA AND ISOSTHENURIA is predicted to treat type 2 diabetes mellitus.'},
  {'confidence': 0.9783447287025961,
   'essence': 'COMPLEMENT COMPONENT C1s DEFICIENCY; C1SD',
   'id': 'https://rtx.ncats.io/api/rtx/v1/result/27428',
   'reasoner_id': 'RTX',
   'result_graph': {'edge_list': [{'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:613783',
      'target_id': 'HP:0005339',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'DOID:9352',
      'target_id': 'HP:0005339',
      'type': 'has_phenotype'}],
    'node_list': [{'description': 'None',
      'id': 'OMIM:613783',
      'name': 'COMPLEMENT COMPONENT C1s DEFICIENCY; C1SD',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_613783'},
     {'description': 'An abnormality of the complement system.',
      'id': 'HP:0005339',
      'name': 'Abnormality of complement system',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0005339'},
     {'description': 'A diabetes mellitus that involves high blood glucose resulting from cells fail to use insulin properly.',
      'id': 'DOID:9352',
      'name': 'type 2 diabetes mellitus',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/DOID_9352'}]},
   'result_type': 'individual query answer',
   'row_data': ['type 2 diabetes mellitus',
    'DOID:9352',
    'COMPLEMENT COMPONENT C1s DEFICIENCY; C1SD',
    'OMIM:613783',
    '0.021655'],
   'text': 'The drug COMPLEMENT COMPONENT C1s DEFICIENCY; C1SD is predicted to treat type 2 diabetes mellitus.'},
  {'confidence': 0.9745126101575119,
   'essence': 'HYPERALPHALIPOPROTEINEMIA 1; HALP1',
   'id': 'https://rtx.ncats.io/api/rtx/v1/result/27429',
   'reasoner_id': 'RTX',
   'result_graph': {'edge_list': [{'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:143470',
      'target_id': 'HP:0012153',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'DOID:9352',
      'target_id': 'HP:0012153',
      'type': 'has_phenotype'}],
    'node_list': [{'description': 'None',
      'id': 'OMIM:143470',
      'name': 'HYPERALPHALIPOPROTEINEMIA 1; HALP1',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_143470'},
     {'description': 'An decrease in the level of triglycerides in the blood.',
      'id': 'HP:0012153',
      'name': 'Hypotriglyceridemia',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0012153'},
     {'description': 'A diabetes mellitus that involves high blood glucose resulting from cells fail to use insulin properly.',
      'id': 'DOID:9352',
      'name': 'type 2 diabetes mellitus',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/DOID_9352'}]},
   'result_type': 'individual query answer',
   'row_data': ['type 2 diabetes mellitus',
    'DOID:9352',
    'HYPERALPHALIPOPROTEINEMIA 1; HALP1',
    'OMIM:143470',
    '0.025487'],
   'text': 'The drug HYPERALPHALIPOPROTEINEMIA 1; HALP1 is predicted to treat type 2 diabetes mellitus.'},
  {'confidence': 0.9588867104947001,
   'essence': 'PANCREATIC AGENESIS 1; PAGEN1',
   'id': 'https://rtx.ncats.io/api/rtx/v1/result/27430',
   'reasoner_id': 'RTX',
   'result_graph': {'edge_list': [{'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0011466',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'DOID:9352',
      'target_id': 'HP:0011466',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:260370',
      'target_id': 'HP:0000857',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0000857',
      'type': 'has_phenotype'}],
    'node_list': [{'description': 'Absence or underdevelopment of the gallbladder.',
      'id': 'HP:0011466',
      'name': 'Aplasia/Hypoplasia of the gallbladder',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0011466'},
     {'description': 'None',
      'id': 'HP:0000857',
      'name': 'Neonatal insulin-dependent diabetes mellitus',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0000857'},
     {'description': 'None',
      'id': 'OMIM:600001',
      'name': 'HEART DEFECTS, CONGENITAL, AND OTHER CONGENITAL ANOMALIES; HDCA',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_600001'},
     {'description': 'A diabetes mellitus that involves high blood glucose resulting from cells fail to use insulin properly.',
      'id': 'DOID:9352',
      'name': 'type 2 diabetes mellitus',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/DOID_9352'},
     {'description': 'None',
      'id': 'OMIM:260370',
      'name': 'PANCREATIC AGENESIS 1; PAGEN1',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_260370'}]},
   'result_type': 'individual query answer',
   'row_data': ['type 2 diabetes mellitus',
    'DOID:9352',
    'PANCREATIC AGENESIS 1; PAGEN1',
    'OMIM:260370',
    '0.041113'],
   'text': 'The drug PANCREATIC AGENESIS 1; PAGEN1 is predicted to treat type 2 diabetes mellitus.'},
  {'confidence': 0.9545250360653231,
   'essence': 'EPIPHYSEAL DYSPLASIA, MULTIPLE, WITH EARLY-ONSET DIABETES MELLITUS',
   'id': 'https://rtx.ncats.io/api/rtx/v1/result/27431',
   'reasoner_id': 'RTX',
   'result_graph': {'edge_list': [{'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0011466',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'DOID:9352',
      'target_id': 'HP:0011466',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:606176',
      'target_id': 'HP:0006274',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:226980',
      'target_id': 'HP:0006274',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0000857',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:606176',
      'target_id': 'HP:0000857',
      'type': 'has_phenotype'}],
    'node_list': [{'description': 'Absence or underdevelopment of the gallbladder.',
      'id': 'HP:0011466',
      'name': 'Aplasia/Hypoplasia of the gallbladder',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0011466'},
     {'description': 'Reduced number of beta cells in the pancreatic islets of Langerhans.',
      'id': 'HP:0006274',
      'name': 'Reduced pancreatic beta cells',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0006274'},
     {'description': 'None',
      'id': 'OMIM:600001',
      'name': 'HEART DEFECTS, CONGENITAL, AND OTHER CONGENITAL ANOMALIES; HDCA',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_600001'},
     {'description': 'None',
      'id': 'HP:0000857',
      'name': 'Neonatal insulin-dependent diabetes mellitus',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0000857'},
     {'description': "Neonatal diabetes mellitus (NDM), defined as insulin-requiring hyperglycemia within the first 3 months of life, is a rare entity, with an estimated incidence of 1 in 400,000 neonates ({16:Shield, 2000}). In about half of the neonates, diabetes is transient (see {601410}) and resolves at a median age of 3 months, whereas the rest have a permanent insulin-dependent form of diabetes (PNDM). In a significant number of patients with transient neonatal diabetes mellitus, type II diabetes (see {125853}) appears later in life ({1:Arthur et al., 1997}). PNDM is distinct from childhood-onset autoimmune diabetes mellitus type I (IDDM; {222100}).\n\n{11:Massa et al. (2005)} noted that the diagnostic time limit for PNDM has changed over the years, ranging from onset within 30 days of birth to 3 months of age. However, as patients with the clinical phenotype caused by mutation in the KCNJ11 gene have been identified with onset up to 6 months of age, {11:Massa et al. (2005)} suggested that the term 'permanent diabetes mellitus of infancy' (PDMI) replace PNDM as a more accurate description, and include those who present up to 6 months of age. The authors suggested that the new acronym be linked to the gene product (e.g., GCK-PDMI, KCNJ11-PDMI) to avoid confusion with patients with early-onset, autoimmune type I diabetes.\n\n{4:Colombo et al. (2008)} proposed that, because individuals with INS gene mutations may present with diabetes well beyond 6 months of age and cannot be distinguished from patients with type 1 diabetes except for the absence of type 1 diabetes autoantibodies, the term PNDM should be replaced with 'monogenic diabetes of infancy (MDI),' a broad definition including any form of diabetes, permanent or transient, with onset during the first years of life and caused by a single gene defect.",
      'id': 'OMIM:606176',
      'name': 'DIABETES MELLITUS, PERMANENT NEONATAL; PNDM',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_606176'},
     {'description': 'Wolcott-Rallison syndrome is a rare autosomal recessive disorder characterized by permanent neonatal or early infancy insulin-dependent diabetes. Epiphyseal dysplasia, osteoporosis, and growth retardation develop at a later age. Other frequent multisystem manifestations include hepatic and renal dysfunction, mental retardation, and cardiovascular abnormalities (summary by {7:Delepine et al., 2000}).',
      'id': 'OMIM:226980',
      'name': 'EPIPHYSEAL DYSPLASIA, MULTIPLE, WITH EARLY-ONSET DIABETES MELLITUS',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_226980'},
     {'description': 'A diabetes mellitus that involves high blood glucose resulting from cells fail to use insulin properly.',
      'id': 'DOID:9352',
      'name': 'type 2 diabetes mellitus',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/DOID_9352'}]},
   'result_type': 'individual query answer',
   'row_data': ['type 2 diabetes mellitus',
    'DOID:9352',
    'EPIPHYSEAL DYSPLASIA, MULTIPLE, WITH EARLY-ONSET DIABETES MELLITUS',
    'OMIM:226980',
    '0.045475'],
   'text': 'The drug EPIPHYSEAL DYSPLASIA, MULTIPLE, WITH EARLY-ONSET DIABETES MELLITUS is predicted to treat type 2 diabetes mellitus.'},
  {'confidence': 0.9535369640709331,
   'essence': 'ISLET CELL ADENOMATOSIS',
   'id': 'https://rtx.ncats.io/api/rtx/v1/result/27432',
   'reasoner_id': 'RTX',
   'result_graph': {'edge_list': [{'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0011466',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'DOID:9352',
      'target_id': 'HP:0011466',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:606176',
      'target_id': 'HP:0006274',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:147630',
      'target_id': 'HP:0006274',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0000857',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:606176',
      'target_id': 'HP:0000857',
      'type': 'has_phenotype'}],
    'node_list': [{'description': 'Absence or underdevelopment of the gallbladder.',
      'id': 'HP:0011466',
      'name': 'Aplasia/Hypoplasia of the gallbladder',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0011466'},
     {'description': 'Reduced number of beta cells in the pancreatic islets of Langerhans.',
      'id': 'HP:0006274',
      'name': 'Reduced pancreatic beta cells',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0006274'},
     {'description': 'None',
      'id': 'OMIM:600001',
      'name': 'HEART DEFECTS, CONGENITAL, AND OTHER CONGENITAL ANOMALIES; HDCA',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_600001'},
     {'description': 'Insulinomatosis and diabetes mellitus syndrome is an autosomal dominant disorder in which affected individuals within a family present with either hyperinsulinemic hypoglycemia secondary to pancreatic neuroendocrine tumors, or a noninsulin-dependent form of diabetes mellitus. A few affected individuals show only impaired glucose tolerance. Some patients also exhibit congenital cataract and/or congenital glaucoma ({2:Iacovazzo et al., 2018}).',
      'id': 'OMIM:147630',
      'name': 'ISLET CELL ADENOMATOSIS',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_147630'},
     {'description': 'None',
      'id': 'HP:0000857',
      'name': 'Neonatal insulin-dependent diabetes mellitus',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0000857'},
     {'description': "Neonatal diabetes mellitus (NDM), defined as insulin-requiring hyperglycemia within the first 3 months of life, is a rare entity, with an estimated incidence of 1 in 400,000 neonates ({16:Shield, 2000}). In about half of the neonates, diabetes is transient (see {601410}) and resolves at a median age of 3 months, whereas the rest have a permanent insulin-dependent form of diabetes (PNDM). In a significant number of patients with transient neonatal diabetes mellitus, type II diabetes (see {125853}) appears later in life ({1:Arthur et al., 1997}). PNDM is distinct from childhood-onset autoimmune diabetes mellitus type I (IDDM; {222100}).\n\n{11:Massa et al. (2005)} noted that the diagnostic time limit for PNDM has changed over the years, ranging from onset within 30 days of birth to 3 months of age. However, as patients with the clinical phenotype caused by mutation in the KCNJ11 gene have been identified with onset up to 6 months of age, {11:Massa et al. (2005)} suggested that the term 'permanent diabetes mellitus of infancy' (PDMI) replace PNDM as a more accurate description, and include those who present up to 6 months of age. The authors suggested that the new acronym be linked to the gene product (e.g., GCK-PDMI, KCNJ11-PDMI) to avoid confusion with patients with early-onset, autoimmune type I diabetes.\n\n{4:Colombo et al. (2008)} proposed that, because individuals with INS gene mutations may present with diabetes well beyond 6 months of age and cannot be distinguished from patients with type 1 diabetes except for the absence of type 1 diabetes autoantibodies, the term PNDM should be replaced with 'monogenic diabetes of infancy (MDI),' a broad definition including any form of diabetes, permanent or transient, with onset during the first years of life and caused by a single gene defect.",
      'id': 'OMIM:606176',
      'name': 'DIABETES MELLITUS, PERMANENT NEONATAL; PNDM',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_606176'},
     {'description': 'A diabetes mellitus that involves high blood glucose resulting from cells fail to use insulin properly.',
      'id': 'DOID:9352',
      'name': 'type 2 diabetes mellitus',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/DOID_9352'}]},
   'result_type': 'individual query answer',
   'row_data': ['type 2 diabetes mellitus',
    'DOID:9352',
    'ISLET CELL ADENOMATOSIS',
    'OMIM:147630',
    '0.046463'],
   'text': 'The drug ISLET CELL ADENOMATOSIS is predicted to treat type 2 diabetes mellitus.'},
  {'confidence': 0.9509911774316819,
   'essence': 'THIAMINE METABOLISM DYSFUNCTION SYNDROME 4 (BILATERAL STRIATAL DEGENERATION AND PROGRESSIVE POLYNEUROPATHY TYPE); THMD4',
   'id': 'https://rtx.ncats.io/api/rtx/v1/result/27433',
   'reasoner_id': 'RTX',
   'result_graph': {'edge_list': [{'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0011466',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'DOID:9352',
      'target_id': 'HP:0011466',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:613710',
      'target_id': 'HP:0005750',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:600001',
      'target_id': 'HP:0000857',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:606176',
      'target_id': 'HP:0000857',
      'type': 'has_phenotype'},
     {'is_defined_by': 'RTX',
      'provided_by': 'BioLink',
      'source_id': 'OMIM:606176',
      'target_id': 'HP:0005750',
      'type': 'has_phenotype'}],
    'node_list': [{'description': 'Absence or underdevelopment of the gallbladder.',
      'id': 'HP:0011466',
      'name': 'Aplasia/Hypoplasia of the gallbladder',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0011466'},
     {'description': 'Thiamine metabolism dysfunction syndrome-4 is an autosomal recessive metabolic disorder characterized by childhood onset of episodic encephalopathy, often associated with a febrile illness, and causing transient neurologic dysfunction. Most patients recover fully, but some may have mild residual weakness. Affected individuals also develop a slowly progressive axonal polyneuropathy beginning in childhood. Brain imaging during the acute episodes shows lesions consistent with bilateral striatal degeneration or necrosis (summary by {1:Spiegel et al., 2009}).\n\nFor a discussion of genetic heterogeneity of disorders due to thiamine metabolism dysfunction, see THMD1 ({249270}).',
      'id': 'OMIM:613710',
      'name': 'THIAMINE METABOLISM DYSFUNCTION SYNDROME 4 (BILATERAL STRIATAL DEGENERATION AND PROGRESSIVE POLYNEUROPATHY TYPE); THMD4',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_613710'},
     {'description': 'None',
      'id': 'OMIM:600001',
      'name': 'HEART DEFECTS, CONGENITAL, AND OTHER CONGENITAL ANOMALIES; HDCA',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_600001'},
     {'description': 'None',
      'id': 'HP:0000857',
      'name': 'Neonatal insulin-dependent diabetes mellitus',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0000857'},
     {'description': "Neonatal diabetes mellitus (NDM), defined as insulin-requiring hyperglycemia within the first 3 months of life, is a rare entity, with an estimated incidence of 1 in 400,000 neonates ({16:Shield, 2000}). In about half of the neonates, diabetes is transient (see {601410}) and resolves at a median age of 3 months, whereas the rest have a permanent insulin-dependent form of diabetes (PNDM). In a significant number of patients with transient neonatal diabetes mellitus, type II diabetes (see {125853}) appears later in life ({1:Arthur et al., 1997}). PNDM is distinct from childhood-onset autoimmune diabetes mellitus type I (IDDM; {222100}).\n\n{11:Massa et al. (2005)} noted that the diagnostic time limit for PNDM has changed over the years, ranging from onset within 30 days of birth to 3 months of age. However, as patients with the clinical phenotype caused by mutation in the KCNJ11 gene have been identified with onset up to 6 months of age, {11:Massa et al. (2005)} suggested that the term 'permanent diabetes mellitus of infancy' (PDMI) replace PNDM as a more accurate description, and include those who present up to 6 months of age. The authors suggested that the new acronym be linked to the gene product (e.g., GCK-PDMI, KCNJ11-PDMI) to avoid confusion with patients with early-onset, autoimmune type I diabetes.\n\n{4:Colombo et al. (2008)} proposed that, because individuals with INS gene mutations may present with diabetes well beyond 6 months of age and cannot be distinguished from patients with type 1 diabetes except for the absence of type 1 diabetes autoantibodies, the term PNDM should be replaced with 'monogenic diabetes of infancy (MDI),' a broad definition including any form of diabetes, permanent or transient, with onset during the first years of life and caused by a single gene defect.",
      'id': 'OMIM:606176',
      'name': 'DIABETES MELLITUS, PERMANENT NEONATAL; PNDM',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/OMIM_606176'},
     {'description': 'None',
      'id': 'HP:0005750',
      'name': 'Contractures of the joints of the lower limbs',
      'type': 'phenotypic_feature',
      'uri': 'http://purl.obolibrary.org/obo/HP_0005750'},
     {'description': 'A diabetes mellitus that involves high blood glucose resulting from cells fail to use insulin properly.',
      'id': 'DOID:9352',
      'name': 'type 2 diabetes mellitus',
      'type': 'disease',
      'uri': 'http://purl.obolibrary.org/obo/DOID_9352'}]},
   'result_type': 'individual query answer',
   'row_data': ['type 2 diabetes mellitus',
    'DOID:9352',
    'THIAMINE METABOLISM DYSFUNCTION SYNDROME 4 (BILATERAL STRIATAL DEGENERATION AND PROGRESSIVE POLYNEUROPATHY TYPE); THMD4',
    'OMIM:613710',
    '0.049009'],
   'text': 'The drug THIAMINE METABOLISM DYSFUNCTION SYNDROME 4 (BILATERAL STRIATAL DEGENERATION AND PROGRESSIVE POLYNEUROPATHY TYPE); THMD4 is predicted to treat type 2 diabetes mellitus.'}],
 'schema_version': '0.8.0',
 'table_column_names': ['input disease name',
  'input disease ID',
  'output disease name',
  'output disease ID',
  'path weight'],
 'terms': {'disease': 'DOID:9352'},
 'tool_version': 'RTX 0.5.4',
 'type': 'medical_translator_query_response'}






